### ISSUE TITLE
Documentation enhancement for scheduler call

### ISSUE THREAD

**Issue by nvindice** [aimeos/aimeos-typo3#104]
This is not _really_ an Aimeos issue, but it might be worth considering to add this to the aimeos setup documentation nevertheless. I just spent 2 hours to figure this out.

For setting up the scheduler, official Typo3 documentation recommends to use this crontab entry:
`*/15 * * * * /usr/local/bin/php /home/user/www/typo3/sysext/core/bin/typo3 scheduler:run`
See [here](https://docs.typo3.org/c/typo3/cms-scheduler/master/en-us/Installation/CronJob/Index.html).

However, **this will not work with Aimeos schedulers**, at least at Typo3 v8 latest and Aimeos 2018.10! All generated links will be invalid, eg: http://mypage.com/home/user/www/typo3/htdocs/product/....

Correct URLs are generated when calling ./cli_dispatch.phpsh scheduler directly from the typo3 path, eg:
`* * * * * cd /home/user/www/typo3 && ./cli_dispatcher.phpsh scheduler`
(version depending).

I suggest adding a note here: https://aimeos.org/docs/TYPO3/Install_Aimeos/Configure_scheduler_tasks to help users set up the scheduler correctly.

(EDIT: updated path)

**Comment by aimeos** [comment]
Is the problem fixed by calling `cli_dispatcher.phpsh` or by changing to the `/home/user/www/typo3/` directory?

**Comment by nvindice** [comment]
Both is necessary.

**Comment by aimeos** [comment]
Done: https://aimeos.org/docs/TYPO3/Install_Aimeos/Configure_scheduler_tasks

Can you please open a bug report at TYPO3 Forge so it will get fixed?

**Comment by nvindice** [comment]
Done: https://forge.typo3.org/issues/88506

**Comment by aimeos** [comment]
Updated your TYPO3 ticket. Hopefully there will be a fix soon
