### ISSUE TITLE
Catalog list - default category - feature request?

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3#108]
A feature request in case my assumption is right (otherwise a clarification is probably needed):

The `catalog list` plugin allows to assign a default category (`Default category if no parameter is available`). It looks like one and only one assignment is recognised, because if there are more than 1 categories assigned, none will be displayed eventually.

If this assumption is correct, it would probably be betteer to:
- use a singular description (currently: "Selected items", better: "Selected Item")
- change the multiple selection field to a single selection field (e.g. like the field right below: `Default sorting of the product list`)

In case my assumption is wrong, then it would be clearer to use a description like
`Default category/categories, if no parameter is available`
And furthermore the module should be checked, because currently, it is totally arbitrary, which products are displayed, when more than 1 category was chosen. 

Thank you!

The screenshots show:
- The category setup (I moved the demo products to their own new "Aimeos Demo Produkte" category)
- Chosen Categories in the backend
- Frontend result (which is in heavy development)

The Frontend shows the demo products, which I moved to the "Aimeos Demo Produkte" category, which is not selected in the plugin. (Actually, it shows all available products...)
 
![Aimeos_category_setup](https://user-images.githubusercontent.com/213803/65947489-b6f01680-e438-11e9-9527-1f3c9f6a0364.png)

![Aimeos_plugin_config](https://user-images.githubusercontent.com/213803/65947418-8a3bff00-e438-11e9-8d84-43d97581727d.png)

![Aimeos_frontend_result](https://user-images.githubusercontent.com/213803/65947430-932cd080-e438-11e9-9297-5a3f02d8f623.png)

**Comment by aimeos** [comment]
Thank you for your hint! Selecting multiple categories is possible so we've changed the text to:
`Default category or categories if no parameter is available`

There was a workaround necessary for TYPO3 to make multiple categories work:
https://github.com/aimeos/ai-client-html/commit/3dd18f0614b5d8fd5fb3c2d6d1d26cbe14091916

Both will be part of the upcoming 19.10 release.

**Comment by rowild** [comment]
I implemented the fix and it works! Thank you very much for your quick response!
