### ISSUE TITLE
German Umlaute in Label lead to Produkt not found error in frontend after update

### ISSUE THREAD

**Issue by linawolf** [aimeos/aimeos-typo3#120]
**Environment**

Version aimeos/aimeos-typo3:2019.10.x-dev
Integration TYPO3 8.7.33
System ddev on windows with php 7.2

**Describe the bug**
Create a product that contains a German Umlaut in the label. 

then update from 18.x to 19.x run the update scripts

The product will be displayed in Listview and Search. However once u click on the link to the single view you get a product not found error

Change the label to only latin letters and the product can be opened. Change the label back to Umlauts and it can be opened.

Create a new Product with an Umlaut in the title and it can be diasplayed

**Comment by aimeos** [comment]
Did you run the index/rebuild job after your upgrade? The layout of the index text table had changed and the product index must be recreated. By saving the product, this has been done for that product automatically. I think saving the product without removing the umlaut character would have the same effect.
