### ISSUE TITLE
Breadcrumb in Singleview produces wrong links

### ISSUE THREAD

**Issue by linawolf** [aimeos/aimeos-typo3#121]
**Environment**

Version aimeos/aimeos-typo3:2019.10.x-dev
Integration TYPO3 8.7.33
System ddev on windows with php 7.2

**Describe the bug**
When I go to Shop -> Kategorien -> Reisen a link like this will be generated:
/your-shop/shop/?ai[f_name]=Reisen&ai[f_catid]=3&ai[controller]=Catalog&ai[action]=list

this one shows all the products in the category. I click on one Product Single Page
i.e. /your-shop/shop/detail/?ai[d_name]=Reise_zum_Schluchsee&ai[d_pos]=0&ai[controller]=Catalog&ai[action]=detail

 However when I am on a Products single page and use the breadcrumb to navigate the category I get a link still pointing to the detail page:
your-shop/shop/detail/?ai[f_name]=Reisen&ai[f_catid]=3&ai[controller]=Catalog&ai[action]=tree
and the message **Produkt "" konnte nicht gefunden werden**

I would expect to get the same link as above when i visited the category directly

**Comment by linawolf** [comment]
This was an update issue. After updating from 18.x to 19.x there is a new field in the flexform of the catalogue stage. "Category page (or catalog list page)" the update script does not fill it. after manually filling it the breadcrumb works for me.
This should be included in the update script

**Comment by aimeos** [comment]
Aimeos can only update it's own tables but doesn't try to change the XML in the tt_content table which is rather difficult. If you do an upgrade between major versions, you should always check the plugins in the pages if they require additional configuration (they are then marked red).
