### ISSUE TITLE
Canonical tags should be handled by EXT:seo (custom handling can probably be removed from aimeos)

### ISSUE THREAD

**Issue by jonaseberle** [aimeos/aimeos-typo3#122]
This unsets the (TYPO3 v9+) core-feature "canonical tags".
https://github.com/aimeos/aimeos-typo3/blob/master/ext_localconf.php#L316
In aimeos 19.10 this is even done unconditionally.

Nowadays there is no real need for custom canonical tags any more. If an URL has a routeEnhancer and EXT:seo is installed, the nice SEO-URL is output as canonical automatically.

If one needs to adapt that, the EXT:seo API could be used:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/MetaTagApi/Index.html#metatagapi

**Comment by aimeos** [comment]
In the latest code, there's already a condition to enable/disable the canonical links from the SEO extension: https://github.com/aimeos/aimeos-typo3/blob/master/ext_localconf.php#L316-L318

The SEO API doesn't allow to disable generating canonical links on a per page basis:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Seo/Index.html

Unfortunately, the TYPO3 route enhancers doesn't work properly and there are a lot of "edge cases" that leads to errors or other problems. Currently, it's extremely hart to create SEO-friendly URLs that are not very basic: https://forge.typo3.org/issues/91098

**Comment by jonaseberle** [comment]
It should be noted that this feature switch disables TYPO3 metaTags site-wide!

**Comment by aimeos** [comment]
Yes. It would be even better if TYPO3 would allow to disable meta tags and canonical URL per page like it was before up to TYPO3 8.
