### ISSUE TITLE
Assigning a product to a category throws type error

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3#123]
When trying to assign a product to a category, this error is thrown:

```
(1/1) TypeError
Argument 1 passed to Aimeos\MShop\Common\Item\Lists\Standard::setPosition() must be of the type int, string given, called in /[path]/ext/ai-admin-jqadm/admin/jqadm/src/Admin/JQAdm/Catalog/Product/Standard.php on line 375
```

This does not happen, when the category is assigned via the product. Checking the category again, the product appears correctly.

aimeos-typo3 20.4.3
TYPO3 9.5.19
php 7.3.18
macOS 10.13.6

Category assignment via the product works fine:
![category assignment via product works fine](https://user-images.githubusercontent.com/213803/84234190-11776180-aaf4-11ea-8d37-4e77bf3bd59c.png)

Products then appear correctly in the assigned category: 
![products appear correctly in category](https://user-images.githubusercontent.com/213803/84234258-2d7b0300-aaf4-11ea-8418-8308fd4b0f9f.png)

**Comment by aimeos** [comment]
This has already been fixed recently. If you use composer, you can install the fix using:
`composer req aimeos/ai-admin-jqadm:2020.04.x-dev`

**Comment by rowild** [comment]
This does not work for me.

I installed the fix via composer (see screenshot)
Updated the database scheme via Extension Manager
Run the DB compare
Cleared out all caches
hard-reloaded the backend
[did I forget something?]

... but the error remains.

Composer install
![Screen Shot 2020-06-10 at 08 34 09](https://user-images.githubusercontent.com/213803/84234838-33251880-aaf5-11ea-9fd0-703ff962d095.png)

Error remains:
![Screen Shot 2020-06-10 at 08 36 47](https://user-images.githubusercontent.com/213803/84235086-8eefa180-aaf5-11ea-9f45-f1bd7806b8fd.png)

**Comment by rowild** [comment]
Was there just another update?

I ran composer again, which checked out 57b54dc501. Now it is working.

(I did restart my server and php before that, so maybe I did something wrong before? xDebug... not removing a breakpoint... not closing a file in VScode... I don't know...)

Anyway: thank you very much!
