### ISSUE TITLE
Categories' "Sorting by relevance" does not work

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3#124]
If I am not mistaken, products should be sorted by their assigned `position`, when the `Catalog list` plugin's `Default sorting of the product list` option is set to `relevance`.

This is, what I have set:
![Catalog list plugin – Sorting option](https://user-images.githubusercontent.com/213803/84244180-8e5e0780-ab03-11ea-9600-97e0f84dd71b.png)

And this is, what the backend shows:
![A category's product list in the backend](https://user-images.githubusercontent.com/213803/84244257-adf53000-ab03-11ea-9110-cc076ea8e0ed.png)

Unfortunately, the FE has its own opinion on how it should sort things:
![Screen Shot 2020-06-10 at 10 19 16](https://user-images.githubusercontent.com/213803/84244406-e268ec00-ab03-11ea-8b81-f1e81fcc7a1f.png)

Am I misunderstanding something here???

TYPO3 9.5.19, aimeos/aimeos-typo3 20.4-dev, php 7.3.18, mac OS 10.13

**Comment by aimeos** [comment]
Strange issue, maybe related to the product index. Can you truncate the mshop_index_catalog table and run the index/rebuild task.

**Comment by rowild** [comment]
That worked - thank you!
