### ISSUE TITLE
Download Preview Images for videos don't work, custom mimeicons dont work either.

### ISSUE THREAD

**Issue by web-commerce-og** [aimeos/aimeos-typo3#129]
I am using 
"aimeos/aimeos-typo3": "2019.10.x-dev",
on TYPO3 8 eLTS
Additionally I had my own extension generated at https://aimeos.org/docs/TYPO3/Extend_Aimeos

When editors upload a video for download the preview Image generated points to an non-existent image:
i.E: /uploads/tx_aimeos/../../typo3conf/ext/aimeos/Resources/Public/Images/Mimeicons/video/webm.png

I had a look in the folder and saw that there are images like "x-generic.png" an I would expect these to be used instead of a non-existing image.

Additionally I tried to supply my own preview images. Through debugging I found out that the preview is defined when uploading the video and then stored in the database and not changed anymore. 
I tried to change the Path for mimetype image by TypoScript:
plugin.tx_aimeos.settings.controller.common.media.standard.mimeicon.directory = ../../typo3conf/ext/wco_aimeos_asw/Resources/Public/Images/Mimeicons
module.tx_aimeos.settings.controller.common.media.standard.mimeicon.directory = ../../typo3conf/ext/wco_aimeos_asw/Resources/Public/Images/Mimeicons

to no avail. 

then I tried to change ist via the generated extension in 
wco_aimeos_asw/Resources/Private/Extensions/wco_aimeos_asw/config/controller.php

`<?php

return [
	'common' => [
	    // common.media.standard.mimeicon.directory = ../../typo3conf/ext/wco_aimeos_asw/Resources/Public/Images/Mimeicons
        'media' => [
            'standard' => [
                'mimeicon' => [
                    'directory' => [
                        '../../typo3conf/ext/wco_aimeos_asw/Resources/Public/Images/Mimeicons'
                    ]
                ]
            ]
        ]
	],
	'frontend' => [
	],
	'jobs' => [
	],
];
`

No matter what I do the images don't get changed. The config array always contains . After changing i deleted all caches and uploaded the video anew. Nothing.

**Comment by aimeos** [comment]
> When editors upload a video for download the preview Image generated points to an non-existent image:
> i.E: /uploads/tx_aimeos/../../typo3conf/ext/aimeos/Resources/Public/Images/Mimeicons/video/webm.png

Not all icons exist for every mime type. We will update the video icons in the next release.

> I had a look in the folder and saw that there are images like "x-generic.png" an I would expect these to be used instead of a non-existing image.

We will see how can we solve this.

> Additionally I tried to supply my own preview images. Through debugging I found out that the preview is defined when uploading the video and then stored in the database and not changed anymore.
> I tried to change the Path for mimetype image by TypoScript:
> module.tx_aimeos.settings.controller.common.media.standard.mimeicon.directory = ../../typo3conf/ext/wco_aimeos_asw/Resources/Public/Images/Mimeicons

TypoScript settings are related to pages but there's none selected when you open the Aimeos backend so your settings won't be passed by TYPO3 to Aimeos.

> 'directory' => [
> '../../typo3conf/ext/wco_aimeos_asw/Resources/Public/Images/Mimeicons'
> ]

It must be:
```
'directory' => '../../typo3conf/ext/wco_aimeos_asw/Resources/Public/Images/Mimeicons'
```

**Comment by aimeos** [comment]
If no icon for the mime type available, the "unknown" icon will be used then.
