### ISSUE TITLE
Sanitize URL parameters: make "_" configurable or use default realurl value "-"

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#13]
Currently names etc. are sanitized in the URL with "_". However, realurl uses "-" by default, though that is configurable but according to PHPdoc deprecated.
It would be good for the URLs to use the same character though over the complete URL.

I was able to solve this for me by doing it like this:
https://aimeos.org/help/typo3-extension-f16/url-sanatize-with-instead-of-t788.html

But it is unnecssarily complex.

**Comment by aimeos** [comment]
Add a product text with type "url segment" to define exactly how the product name in the URL should look like.
