### ISSUE TITLE
CKEditor not working in the backend

### ISSUE THREAD

**Issue by guelzow** [aimeos/aimeos-typo3#130]
Hi everyone.

The CKEditor is trying to load the following files from the TYPO3 installation:

1. typo3/config.js
2. typo3/lang/de.js
3. typo3/skins/moono-lisa/editor_gecko.css

Since these files are not there, it gets a 404, and exits with a 
```javascript
Uncaught TypeError: c[a] is undefined
```

Adding a 
```html
<script>
    CKEDITOR_BASEPATH = 'https://cdn.jsdelivr.net/npm/ckeditor@4/';
</script>
```
here: https://github.com/aimeos/aimeos-typo3/blob/master/Resources/Private/Layouts/Jqadm.html#L18
should point the editor to the right direction.

Tobi

**Comment by aimeos** [comment]
Thanks, problem has been fixed in 2020.07.x-dev: https://github.com/aimeos/aimeos-typo3/commit/681170f9ad4cd48f3b2967c917555f3119369347
