### ISSUE TITLE
Product assignments to categories are noch visible in frontend

### ISSUE THREAD

**Issue by bitmotionAE** [aimeos/aimeos-typo3#131]
Hi! When editing a product record and adding it to categories, the change is visible in frontend directly.
If you go the other way and edit a category, for which you select products, the change is not visible in frontend. The reason is probably that when editing a category record the table "mshop_index_catalog" is not updated.
Is there a fix besides running the scheduler which rebuilds the index?

**Comment by aimeos** [comment]
Which Aimeos version do you use? In 2020.07 the problem has been fixed:
https://github.com/aimeos/ai-admin-jqadm/blob/2020.07/admin/jqadm/src/Admin/JQAdm/Common/Decorator/Index.php
