### ISSUE TITLE
Wrong constant name in the configuration

### ISSUE THREAD

**Issue by guelzow** [aimeos/aimeos-typo3#132]
Hi everyone.

I've found a small one.

Here https://github.com/aimeos/aimeos-typo3/blob/master/Configuration/TypoScript/setup.txt#L2
The constant name `{$plugin.tx_aimeos.theme.css.custom}` is used.

But here https://github.com/aimeos/aimeos-typo3/blob/master/Configuration/TypoScript/constants.txt#L7
The constant name `plugin.tx_aimeos.theme.css.aimeos-custom` is used.

Tobi

**Comment by aimeos** [comment]
> Here https://github.com/aimeos/aimeos-typo3/blob/master/Configuration/TypoScript/setup.txt#L2
> The constant name `{$plugin.tx_aimeos.theme.css.custom}` is used.

Thanks for your hint! Can you create a PR fixing that name?
