### ISSUE TITLE
fail Installing sjbr/static-info-tables with composer

### ISSUE THREAD

**Issue by ottovb** [aimeos/aimeos-typo3#138]
using the composer command: composer req aimeos/aimeos-typo3:~20.10
a failure is thrown with  - Installing sjbr/static-info-tables (v6.9.0): Cloning fc7f46b386

At extension Static Info Tables (https://forge.typo3.org/issues/89356) a bug is present No installation possible with Composer (Bug #89356) since a year.

What is a good workaround?

Kind regards, Otto van Bruggen

**Comment by aimeos** [comment]
This isn't a general problem and it usullay works without problems.
Please make sure your `composer.json` doesn't contain a `repository` section with a `git.typo3.org` entry so always packagist.org is used and not the TYPO3 Git repository.

**Comment by ottovb** [comment]
thank you solved it!
