### ISSUE TITLE
overlapping w/ typo3 class-resolver

### ISSUE THREAD

**Issue by xerc** [aimeos/aimeos-typo3#144]
PHP Warning: file_exists(): open_basedir restriction in effect.
File(/opt/php_7.4.8/lib/php/TYPO3/CMS/Fluid/ViewHelpers/LayoutViewHelper.php) 
```
autoload( TYPO3\CMS\Fluid\ViewHelpers\LayoutViewHelper )
  get_include_path() => .:/opt/php_7.4.8/lib/php
```
Aimeos\Bootstrap::autoload() https://github.com/aimeos/aimeos-core/blob/master/Bootstrap.php#L80
spl_autoload_call()
class_exists() https://github.com/TYPO3/Fluid/blob/master/src/Core/ViewHelper/ViewHelperResolver.php#L329

**Comment by aimeos** [comment]
open_basedir is not supported by Aimeos and must be turned off

**Comment by xerc** [comment]
ok // please consider to not-use "allow_url_fopen" too

**Comment by aimeos** [comment]
Aimeos doesn't rely on it as far as I know but it may be necessary if you add e.g. external URL for images to the database to create the preview images.

**Comment by xerc** [comment]
![Bildschirmfoto 2020-11-17 um 16 06 30](https://user-images.githubusercontent.com/1372590/99406999-e6890900-28ee-11eb-925d-425ee86b8b49.png)

**Comment by aimeos** [comment]
It's a warning only and is likely to work without for most cases. If you find places where it doesn't work, drop us a note.

**Comment by xerc** [comment]
ok // THX
