### ISSUE TITLE
Question: How to deactivate HTML-Emails and send Text-Emails only

### ISSUE THREAD

**Issue by phasenraum2010** [aimeos/aimeos-typo3#15]
Question: 
How can I deactivate HTML-Emails and send Text-Emails only?

**Comment by aimeos** [comment]
Sure, just configure only the text subpart for e.g. the payment related e-mails:
https://aimeos.org/docs/Configuration/Core/client/html/email/payment/standard/subparts

**Comment by phasenraum2010** [comment]
Sorry, but where do I find the Subparts in the last TER-Release?
