### ISSUE TITLE
Error running update script (v19 to 20)

### ISSUE THREAD

**Issue by loeffe1** [aimeos/aimeos-typo3#151]
`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("domain_stage"."#sql-2d2_17e4", CONSTRAINT "fk_msattli_pid" FOREIGN KEY ("parentid") REFERENCES "mshop_attribute" ("id") ON DELETE CASCADE ON UPDATE CASCADE): ALTER TABLE mshop_attribute_list ADD CONSTRAINT fk_msattli_pid FOREIGN KEY (parentid) REFERENCES mshop_attribute (id) ON UPDATE CASCADE ON DELETE CASCADE
#0 /var/www/domain/htdocs/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Task/Base.php(164): Aimeos\MW\DB\Statement\DBAL\Simple->execute()
#1 /var/www/domain/htdocs/vendor/aimeos/aimeos-core/lib/mshoplib/setup/TablesCreateMShop.php(175): Aimeos\MW\Setup\Task\Base->executeList(Array, 'db-attribute')
#2 /var/www/domain/htdocs/vendor/aimeos/aimeos-core/lib/mshoplib/setup/TablesCreateMShop.php(87): Aimeos\MW\Setup\Task\TablesCreateMShop->setupSchema(Array)
#3 /var/www/domain/htdocs/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(114): Aimeos\MW\Setup\Task\TablesCreateMShop->migrate()
#4 /var/www/domain/htdocs/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(110): Aimeos\MW\Setup\Manager\Multiple->migrateTasks(Array, Array)
#5 /var/www/domain/htdocs/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(82): Aimeos\MW\Setup\Manager\Multiple->migrateTasks(Array)
#6 /var/www/domain/htdocs/public/typo3conf/ext/aimeos/Classes/Setup.php(74): Aimeos\MW\Setup\Manager\Multiple->migrate()
#7 /var/www/domain/htdocs/var/transient/ext_update29058efd0b9b5057aa934971eb735b47.php(54): Aimeos\Aimeos\Setup::execute()
#8 /var/www/domain/htdocs/public/typo3/sysext/extensionmanager/Classes/Utility/UpdateScriptUtility.php(41): ext_update29058efd0b9b5057aa934971eb735b47->main()
#9 /var/www/domain/htdocs/public/typo3/sysext/extensionmanager/Classes/Controller/UpdateScriptController.php(52): TYPO3\CMS\Extensionmanager\Utility\UpdateScriptUtility->executeUpdateIfNeeded('aimeos')
#10 /var/www/domain/htdocs/public/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(318): TYPO3\CMS\Extensionmanager\Controller\UpdateScriptController->showAction('aimeos')
#11 /var/www/domain/htdocs/public/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(167): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod()
#12 /var/www/domain/htdocs/public/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php(73): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->processRequest(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response))
#13 /var/www/domain/htdocs/public/typo3/sysext/extbase/Classes/Mvc/Web/BackendRequestHandler.php(35): TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response))
#14 /var/www/domain/htdocs/public/typo3/sysext/extbase/Classes/Core/Bootstrap.php(217): TYPO3\CMS\Extbase\Mvc\Web\BackendRequestHandler->handleRequest()
#15 [internal function]: TYPO3\CMS\Extbase\Core\Bootstrap->handleBackendRequest(Object(TYPO3\CMS\Core\Http\ServerRequest))
#16 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Http/RouteDispatcher.php(93): call_user_func_array(Array, Array)
#17 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Http/RequestHandler.php(73): TYPO3\CMS\Backend\Http\RouteDispatcher->dispatch(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(TYPO3\CMS\Core\Http\Response))
#18 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Middleware/SiteResolver.php(59): TYPO3\CMS\Backend\Http\RequestHandler->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#19 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\SiteResolver->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(TYPO3\CMS\Backend\Http\RequestHandler))
#20 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Middleware/AdditionalResponseHeaders.php(39): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#21 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\AdditionalResponseHeaders->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#22 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Middleware/OutputCompression.php(45): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#23 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\OutputCompression->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#24 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Middleware/LegacyBackendTemplateInitialization.php(42): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#25 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\LegacyBackendTemplateInitialization->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#26 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Middleware/BackendUserAuthenticator.php(70): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#27 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\BackendUserAuthenticator->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#28 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php(73): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#29 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\BackendRouteInitialization->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#30 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(53): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#31 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\ForcedHttpsBackendRedirector->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#32 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php(71): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#33 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Backend\Middleware\LockedBackendGuard->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#34 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(58): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#35 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\CMS\Core\Middleware\NormalizedParamsAttribute->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#36 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(67): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#37 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(108): TYPO3\CMS\Core\Http\MiddlewareDispatcher->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#38 /var/www/domain/htdocs/public/typo3/sysext/backend/Classes/Http/Application.php(68): TYPO3\CMS\Core\Http\AbstractApplication->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#39 /var/www/domain/htdocs/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): TYPO3\CMS\Backend\Http\Application->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#40 /var/www/domain/htdocs/public/typo3/index.php(24): TYPO3\CMS\Core\Http\AbstractApplication->run()
#41 /var/www/domain/htdocs/public/typo3/index.php(25): {closure}()
#42 {main}`

**Comment by aimeos** [comment]
Seems like you have records in your mshop_attribute_list table without corresponding records in your mshop_attribute table. You have to remove them first before creating the foreign key will work.

Guess, you are using TYPO3 and removed the FK constraints in the install tool some time ago.
