### ISSUE TITLE
[Composer Setup] Not working with a fresh typo3 v10 install

### ISSUE THREAD

**Issue by graseggergh** [aimeos/aimeos-typo3#154]
# The Problem 

**Symptom**: `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.mshop_locale_site' doesn't exist: SELECT "siteid", "label", "nleft", "nright" FROM "mshop_locale_site" ORDER BY "nleft"`

**My Guess**: Migrations are not run

** Possibly related issues:**
#86 (I had the same error of the missing Extension folder until I moved the aimeos setup *above* the typo3cms install command)

## How do I know it's not a ddev problem?

The problem is not coming from the server setup. When using the hosts composer the same errors come up. 

## How do I know it's not a typo3 problem?

When removing the aimeos dependency and commands you get a working typo3 setup.

# How to reproduce

Clone [my test repo](https://github.com/graseggergh/typo3-test) and execute `ddev start`. Or you can use any server and execute `composer install`.

**Comment by aimeos** [comment]
The problem is solved by this PR: https://github.com/aimeos/aimeos-typo3/pull/153
We release a new version today.

**Comment by graseggergh** [comment]
@aimeos Great news, thanks!
