### ISSUE TITLE
Checkout fails on aimeos extension

### ISSUE THREAD

**Issue by roccoh** [aimeos/aimeos-typo3#157]
I have a fresh TYPO3 installation with composer.
Bootstrap-Package 10.4.9 as main site
Aimeos 20.10.4 as extension

The checkout process fails, because no products are passed into the basket.

I have made a test with another TYPO3 composer installation.
At this time with aimeos 10.4.11 as main site.
The checkout works as expected.

Is there a workaraound to solve the problem on the extension?
Kind regards
Rocco

**Comment by aimeos** [comment]
Does the detail page link to the right basket page in the flexform of the catalog detail component?

**Comment by roccoh** [comment]
Jes, it does.
I verified it with the aimeos-installation. All plugins are linked on the same way.

**Comment by aimeos** [comment]
So you think it's a bootstrap_package problem?
Is the product added to the basket at all or does nothing happen if you click on the "Add to basket" button in the detail view?

**Comment by roccoh** [comment]
That is exactly what happens. The product is not added to the basket. Therefore the checkout process is interrupted after filling the address an delivery option.
I do not know, if it is a bootstrap problem. As i see, the aimeos-distribution is also including the bootstrap-package.

**Comment by roccoh** [comment]
Does anyone have an idea what could be the problem in this case? 

My observations after the installations with composer are as follows.

**Bootstrap-Package with Aimeos-Extension:**
Works well, until it comes to the checkout (no import to the basket).

**Aimeos-Distribution including Bootstrap-Package:**
Did not work at all. Reason: No database tables for Aimes had been created.

Therefore I importet the aimeos-tables from the Bootstrap-Package with Aimos-Extension into the Aimeos-Distribution database.
After that, Aimeos works as expected for the Aimeos-Distribution.

My conclusion: Bootstrap-Package is probably not the problem.

Does it help to solve this problem or did I something wrong?

**Comment by aimeos** [comment]
The database tables in the distribution are usually created when activating the extension. If that was not the case for any reason, you can execute the update script in the extension manager.

**Comment by roccoh** [comment]
Thank you for your input.
I am almost certain, that I activated the Aimeos distribution (no database tables for Aimeos have been created).
If this has been solved in the meantime, is good to know. Unfortunately does it not solve the current problem with the Aimeos extension (no import to the basket during the checkout process).
I very appreciate, if you could help me.

**Comment by aimeos** [comment]
Hard to say without a test installation where we can reproduce the problem.
Is your installation publically available?

**Comment by roccoh** [comment]
Yes, you can see the installation:
http://bootstrap10.ch.nova.ch-meta.net/

If you want to have a look into the backend:
http://bootstrap10.ch.nova.ch-meta.net/typo3
User: aimeos
Password: aimeos

Many thanks and kind regards

**Comment by aimeos** [comment]
TYPO3 FE-User cookies are using the "secure" attribute and you need a HTTPS so the browser sends the cookie.

**Comment by roccoh** [comment]
This is not the case by the Aimeos-Distribution. It works under the same conditions and completes the checkout process with a insecure HTTP connection. I cannot understand, why the "secure" attribute should take over at the Aimeos-Extension and not on the Aimeos-Distribution. I guess, the TYPO3 FE-User cookies are working the same.

This difference is important. I cannot publish my project with a secure protocol until I go live with the website.
"It will work already" is on my opinion not sufficient to convince me and my customer.

**Comment by aimeos** [comment]
Can only tell you that the browser displays a warning in the browser console that the cookie isn't sent because your TYPO3 installation. You can try to disable secure cookies on your test server: https://t3terminal.com/blog/typo3-security/#c2043

**Comment by roccoh** [comment]
Maybe I am unable to see the problem.

I have two installations that can be reached online for testing.
Both of them are dependent on the secure settings of the host.
You can verify, how the two installations are working differently.

Aimeos-Distribution with BootstrapPackage-Extension:
http://aimeos10.ch.nova.ch-meta.net
Goes through the checkout process.

BootstrapPackage-Distribution width Aimeos-Extension:
http://bootstrap10.ch.nova.ch-meta.net
The "fe_typo_user" cookie was rejected. Therefore the checkout process is interrupted.

As both versions depend on the BootstrapPackage, it only makes sense to me that both should work the same way.

Again, I cannot present a solution to my client that is not working. A hint that everything will work after going live doesn't really help me and makes me unsure whether that will be the case.

Do you have any solution to solve ist?

**Comment by aimeos** [comment]
Like said, try to disable secure cookies in your TYPO3 LocalConfiguration.php

**Comment by roccoh** [comment]
That information helped me.

Setting "cookieSecure" on "0" did not change anything, because it is already the TYPO3 standard setting.

The problem was, that "cookieSameSite" was set on "none" at the BootstrapPackage-Distribution.
By resetting (deleting) the standard setting, the problem is resolved.

Many thanks for your help and kind regards.
