### ISSUE TITLE
Missing mimetype-icons in BE/FE

### ISSUE THREAD

**Issue by stephankellermayr** [aimeos/aimeos-typo3#158]
If you are uploading files to products and mark them as **download** (pdf, zip, ...), there is no mimetype-icon available (Frontend and Backend).
It just selects `unknown.png`, because the relative path given in `controller/common/media/standard/mimeicon/directory` cannot be resolved correctly with `file_exists()` in https://github.com/aimeos/aimeos-core/blob/1718389a5908bb5000105f815c724d5792297a72/controller/common/src/Controller/Common/Media/Standard.php#L506

Any suggestions?

**Comment by aimeos** [comment]
What does the variable `$mimedir` contains in your case?

**Comment by stephankellermayr** [comment]
In this case it contains the default value `../../typo3conf/ext/aimeos/Resources/Public/Images/Mimeicons`, defined in `controller/common/media/mimeicon/directory`

**Comment by aimeos** [comment]
Should be changed here I think: https://github.com/aimeos/aimeos-typo3/blob/7069b5048c8badd5b31ca1731ad53fad1237538a/Resources/Private/Config/controller.php#L11
Can you create a PR for the required change?

**Comment by stephankellermayr** [comment]
Yes, absolutely, but to which value? The Problem is, that the final img-tag refers to a path relative to docroot, but `file_exists()` requires an absolute path in this case. Or did i miss something?

**Comment by aimeos** [comment]
Paths for file_exists() can also be relative, the problem is if the current working directory is the same as the document root which may not always be the case ...

**Comment by stephankellermayr** [comment]
...this seems to be true in this particular case: i am using TYPO3 as a symlinked source in another directory, that's why the relative path cannot be resolved. But how this can be solved? Changes in `aimeos-core` are not what we want and changing only the value in `controller/common/media/standard/mimeicon/directory` does not solve the problem, because if the path can be resolved, it is directly returned as img-tag, which of course does not work.

**Comment by aimeos** [comment]
Problem is that it's best to use the real path to check for existence (if symlinks are used) and a path relative to the document root for the browser. I guess there's no solution without changing the core code and either use two configuration options or remove the `file_exists()` check (which will lead to broken icons for unknown file types).
