### ISSUE TITLE
[Feature Request] Allow @'import notation in the scheduler Tasks

### ISSUE THREAD

**Issue by guelzow** [aimeos/aimeos-typo3#159]
Hi everyone.

"As an integrator, I want to use the @'import notation in the scheduler TypoScript tasks."
This means, that we can set up a global TypoScript file, that then can get used by the scheduler.

**Proposed solution:**
The TypoScriptParser class provides the static method 'checkIncludeLines', that can be used to pre-parse the scheduler typoscript.

Replacing this line
https://github.com/aimeos/aimeos-typo3/blob/20.10.5/Classes/Base.php#L239
with
```php
$parser->parse( TypoScriptParser::checkIncludeLines( $tsString ) );
```
should do the trick.

Tobi

**Comment by aimeos** [comment]
Cool, can you create a PR for that?

**Comment by guelzow** [comment]
Sure.
