### ISSUE TITLE
throwPageNotFoundExceptionIfActionCantBeResolved and skipDefaultArguments

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#16]
If using throwPageNotFoundExceptionIfActionCantBeResolved = 1 

`
plugin.tx_aimeos {
    mvc {
        throwPageNotFoundExceptionIfActionCantBeResolved = 1
    }
}
`

then the detail view results in an exception.

The reason is that the controller parameter has "catalog" as value but it should be "**C**atalog" instead. There probably exist other scenarios and as one can set this setting per extension it isn't that problematic. However, if I modify the default option and don't override the value manually it results in an exception.

**Comment by aimeos** [comment]
Why would you like to use this setting? By default, this one is used instead:
`callDefaultActionIfActionCantBeResolved = 1`

**Comment by AndreasA** [comment]
1.) The point is that even if I don't want to use the setting, the controller parameter is still wrong.
This might be the reason why `features.skipDefaultArguments = 1` doesn't remove the controller and action parameter from the URL as it can't find it.

2.) If throwPageNotFoundExceptionIfActionCantBeResolved  is set then it has priority over callDefaultActionIfActionCantBeResolved 

3.) One reason for this setting is to avoid duplicate URLs for the same view, e.g. by using wrong parameters which is a bit relevant in regards to SEO but might not be the only reason. Another might be to just know you use wrong parameters (during development).

**Comment by aimeos** [comment]
Good point! We should make this working in TYPO3.

The alternative would be to change all "controller" configuration settings. Personally, I would opt for ucfirst() because it's only relevant for TYPO3 and this solution would make it more fault tolerant if developers configure one of the controller settings by hand.

Are you able to create a pull request for this?

**Comment by AndreasA** [comment]
Would ucfirst be enough or can there be upper case characters further in the parameter name too which might be lowercase?

I can create a PR, probably sometime this weekend where I will work further with aimeos again.

**Comment by aimeos** [comment]
What about the action? Does the first character have to be in upper case too? For the rest I think not

**Comment by AndreasA** [comment]
Action is small, the values basically have to be those that are defined in ext_localconf.php

**Comment by AndreasA** [comment]
didn't find the time to create the PR (and test it), so it will be sometime the coming week. Probably Tuesday.

**Comment by AndreasA** [comment]
Will probably finish this tonight.
It could be that clearing the realurl cache is required to avoid issues when activating skipDefaultArguments too.

**Comment by AndreasA** [comment]
I probably will not find the time to finish it today but I have a question anyway first:

In regards to support for skipDefaultArguments, I think the easiest solution is to create a child class of UriBuilder overwrite the build() method to detect FE / BE according to aimeos and then use uriFor.

Any reasons against it? If not, I will implement it sometime this week.

**Comment by aimeos** [comment]
I don't think you have to subclass the TPYO3 UriBuilder because we can pass a configuration to the Aimeos url() view helper (config: "BE") to mark URLs that must be created for the backend:
https://github.com/aimeos/ai-typo3/blob/master/lib/custom/src/MW/View/Helper/Url/Typo3.php#L92

Does anything change in the frontend URLs if you remove the "bypass" RealURL option? For the 'ai[f_sort]' parameter we still need it, doesn't we?

**Comment by AndreasA** [comment]
Yes. I know about this check. However, various features like skipDefaultArguments is only used when calling uriFor method
and that method calls the build method automatically at the end, so I cannot differentiate between BE and FE prior to uribuilder.

Another possibiltiy would be to add the code of the method for skipDefaultArguments to the Typo3 URL helper but I think it is better to use its default implementation instead of always keeping it up-to-date :)

In regards to bypass I meant only for controller and action as those should then be gone always anyway.

In our case it probably doesn't make much difference as we don't use / need cHash but with cHash and bypass it could result in cHash troubles if the same URL is once called with the parameter and once without.

**Comment by aimeos** [comment]
What if we simply use `uriFor()` again for frontend URLs?
https://github.com/aimeos/ai-typo3/blob/master/lib/custom/src/MW/View/Helper/Url/Typo3.php#L96

**Comment by AndreasA** [comment]
We still sould have to override it because build in uriFor doesn't ensure that we will get a Frontend-URL.
e.g. Scheduler Tasks would then always produce a Backend-URL.

So I think the best case is still to override the build method. 
The question might be if I only build the frontend URL then, and keep the BE check in the Typo3 and T3Cli class.

**Comment by aimeos** [comment]
For FE URLs generated by the scheduler tasks, the T3Cli class is always used. This is due to an incomplete environment setup in TYPO3 6.2 and at least up to 7.6 which causes fatal errors:
https://forge.typo3.org/issues/67355

**Comment by AndreasA** [comment]
However, the check regarding BE is still different in aimeos, so it could be possible a backend URL is generated but I want a frontend URL. The best way to avoid is, is to move the check in a own UriBuilder class.

T3cli doesn't use uribuilder at all but manually builds the URL without speaking URLs?

I think  this should be modified too to correctly initialize the UriBuilder instead (as is done in the last comment)

I could try to get this to work when extending the UriBuilder for aimeos? (Though it might be a separate PR)

**Comment by aimeos** [comment]
Please feel free to enhance the integration :-)

**Comment by AndreasA** [comment]
As mentioned in another ticket. I was kinda busy until now. I think I would take a look at this at the same time as the other issue.

**Comment by aimeos** [comment]
We've added both settings to the Aimeos TS configuration. The UriBuilder is used for generating links in the e-mails and the first char of the controller name is upper cased. All changes are part of dev-master now. I think we are done now, aren't we?

**Comment by AndreasA** [comment]
I will verify and let you know. The same timeframe applies though :)

**Comment by AndreasA** [comment]
Same as with #19

Will also try to update our shop to newest aimeos version then :)
