### ISSUE TITLE
Demoinstallation von Aimeos versendet keine Mails

### ISSUE THREAD

**Issue by ummSaarland** [aimeos/aimeos-typo3#161]
**Environment**
1. Version 21.10.5
2. Integration TYPO3,
3. System (Linux)

**Describe the bug**
Demoinstallation von Aimeos versendet keine Mails
http://webshop.rvs-projekte.de

**Comment by aimeos** [comment]
Did you configure the scheduler task like described here?
https://aimeos.org/docs/latest/typo3/setup/#cronjobs

**Comment by ummSaarland** [comment]
... dankeschön.
