### ISSUE TITLE
"Your new account" email

### ISSUE THREAD

**Issue by linawolf** [aimeos/aimeos-typo3#163]
We have trouble with the "Your new account" email.

The link to the login page is broken ( http://www.example.de/var/www/typo3/xyz/web/typo3/sysext/core/bin/webshop/mein-account/?ai%5Bcontroller%5D=Account&ai%5Baction%5D=index)

and also the mail is in english even though other mails send by aimeos are in German as desired.

We are using aimeos 19.10.12 on TYPO3 LTS 8.

**Comment by aimeos** [comment]
All URLs are generated by TYPO3 exclusively and that usually works without problems. Check if you use the "Advanced Aimeos scheduler task" because it's the only one that can generate links.
