### ISSUE TITLE
Correct the labels in the ext_conf_template

### ISSUE THREAD

**Issue by guelzow** [aimeos/aimeos-typo3#165]
Hi everyone.

Aimeos ships with extension settings, located in the ext_conf_template.txt.

Two labels in there are switched:
![Switches labels](https://user-images.githubusercontent.com/11192910/118232080-59370380-b490-11eb-84c0-fc05ca05ecdb.png)

This can be rather confusing for integrators.

Proposed solution:
Simply switch line 17 and 15 [here](https://github.com/aimeos/aimeos-typo3/blob/master/ext_conf_template.txt).

Tobi

**Comment by aimeos** [comment]
Sure, can you make a PR?
