### ISSUE TITLE
Installation width composer 2.0.14 fails

### ISSUE THREAD

**Issue by roccoh** [aimeos/aimeos-typo3#167]
After upgrading to macOS Big Sur I cannot anymore whether install nor update aimeos. No problems with other extensions.

This is the output after installing:

- composer/installers v1.0.22 requires composer-plugin-api 1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
- composer/installers[v1.0.23, ..., v1.8.0] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
- aimeos/ai-client-html[2021.04.1, ..., 2021.04.2] require tecnickcom/tcpdf dev-main -> found tecnickcom/tcpdf[dev-main] but it does not match your minimum-stability.
- aimeos/aimeos-typo3[21.4.1, ..., 21.4.2] require aimeos/ai-client-html 2021.04.* -> satisfiable by aimeos/ai-client-html[2021.04.1, ..., 2021.04.10].
- aimeos/ai-client-html[2021.04.3, ..., 2021.04.10] require composer/installers ^1.0 -> satisfiable by composer/installers[v1.0.0, ..., v1.11.0].
- typo3/cms-composer-installers v3.1.1 conflicts with composer/installers v1.11.0.
- typo3/cms-composer-installers v3.1.1 conflicts with composer/installers v1.10.0.
- typo3/cms-composer-installers v3.1.1 conflicts with composer/installers v1.9.0.   
...
- typo3/cms-core v10.4.16 requires typo3/cms-composer-installers ^2.0 || ^3.0 -> satisfiable by typo3/cms-composer-installers[v3.1.1].
- typo3/cms-core is locked to version v10.4.16 and an update of this package was not requested.
- Root composer.json requires aimeos/aimeos-typo3 ^21.4 -> satisfiable by aimeos/aimeos-typo3[21.4.1, 21.4.2].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

Can someone help me? 
Many thanks in advance.

**Comment by aimeos** [comment]
Installing Aimeos in TYPO3 only works with composer v1 due to restrictions in TYPO3.

**Comment by roccoh** [comment]
Okay, thank you for the input.
