### ISSUE TITLE
Language is incorrect when switching from dashboard directly to products

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#17]
If one switches from dashboard directly to products without doing anything else, then the language is always 'en' because the link to 'products' includes the lang parameter and the lang parameter wasn't set when calling the dashboard.

If one goes first to expert mode and then back to simple mode the lang parameter seems to be set and therefore the switch to products works with the correct language.

Simplest solution is probably to modify "ai-admin-jqadm/admin/jqadm/templates/common/page-default.php" 
to use instead of:
`$params['lang'] = $this->param( 'lang', 'en' );`

`$params['lang'] = $this->param( 'lang', null );`

Or to set the lang parameter when creating the View.

**Comment by aimeos** [comment]
Good catch! Can you create a pull request including the change?
Maybe we can leave out the lang parameter completely if not set.

**Comment by AndreasA** [comment]
Can create one. However, it would then probably be in ai-jqadm instead I guess.

Will create it at the same time I create the one for https://github.com/aimeos/aimeos-typo3/issues/16

Sorry to say I wasn't able to create it today, so it will probably be Friday / Saturday.

**Comment by AndreasA** [comment]
PR created: https://github.com/aimeos/ai-admin-jqadm/pull/3

**Comment by AndreasA** [comment]
Resolved with mentioned PR.
