### ISSUE TITLE
Incompatibility to Typo3 v10.4.19

### ISSUE THREAD

**Issue by nvindice** [aimeos/aimeos-typo3#171]
**Environment**
1. Version: 2021.07
2. Integration Typo3

**Describe the bug**
With Typo3 v10.4.19, lots of HTML code is displayed in most parts of the admin dashboard because of some encoding problem (`&lt;` instead of `<`). This seems to correspond directly to https://typo3.org/security/advisory/typo3-core-sa-2021-013

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18614852/128856966-f9598eff-0d46-4917-a417-e9822ccd8679.png)

**Comment by aimeos** [comment]
Does replacing that line with "{content}" only fixes the problem?
https://github.com/aimeos/aimeos-typo3/blob/master/Resources/Private/Templates/Jqadm/Search.html#L3

**Comment by aimeos** [comment]
Can you try `aimeos/aimeos-typo3:2021.07.x-dev`?

**Comment by nvindice** [comment]
Problem solved, thank you!
