### ISSUE TITLE
Omnipay Postfinance

### ISSUE THREAD

**Issue by roccoh** [aimeos/aimeos-typo3#172]
Dears
I need help. Is there a way to integrate the Omnipay Postfinace into the shop?
My system:
TYPO3 10 composer
Latest Aimeos Shop.
Can someone help me?
Thanks in advance

**Comment by aimeos** [comment]
Please see: https://aimeos.org/docs/latest/manual/services/#postfinance

For further questions, please ask for help in the Aimeos forum: https://aimeos.org/help
