### ISSUE TITLE
Json api alwas returns "use options method..." error

### ISSUE THREAD

**Issue by Blechlawine** [aimeos/aimeos-typo3#174]
It doesn't seem to care about any parameters. I tried nested parameters and not nested, both produce the same response. I used the options method to retrieve the urls for the resources and now I am trying to get the catalog resource. If you need any more information, i'll happily provide it. Thanks in advance for helping.

**Comment by aimeos** [comment]
GET is not available for /jsonapi, only OPTIONS. OPTIONS response will contain links to the resources you can use GET on

**Comment by aimeos** [comment]
Did you read https://aimeos.org/docs/latest/frontend/jsonapi/ regarding nested parameters?

**Comment by Blechlawine** [comment]
> Did you read https://aimeos.org/docs/latest/frontend/jsonapi/ regarding nested parameters?

Yes, I did read that and I also tried nested parameters exactly like "ai[resource]=catalog", which my url in the options response said. And that didn't work.

**Comment by aimeos** [comment]
Please post your used URLs

**Comment by Blechlawine** [comment]
my url is: "/api?ai[resource]=catalog&ai[action]=options&ai[controller]=Jsonapi", but url encoded.

**Comment by aimeos** [comment]
What's the response of the OPTIONS request sent to /api?

**Comment by Blechlawine** [comment]
> What's the response of the OPTIONS request sent to /api?

exactly that url

**Comment by aimeos** [comment]
And what's exactly the response of GET /api?ai[resource]=catalog&ai[action]=options&ai[controller]=Jsonapi

**Comment by Blechlawine** [comment]
{
  "errors": {
    "title": "Use OPTIONS method for the resource list",
    "detail": "This is the Aimeos JSON REST API\n\nUse the HTTP OPTIONS method to retrieve a list available resources from /api?ai%5Baction%5D=options&ai%5Bcontroller%5D=Jsonapi\nDocumentation about he Aimeos JSON REST API is available at https://aimeos.org/docs/Developers/Client/JSONAPI"
  }
}

**Comment by Blechlawine** [comment]
Ok, so i started with a new installation of typo3, and without changing anything or adding any pages, installed aimeos. Now it works. I still dont know why, but it seems my previous installation of typ3 or aimeos was somehow scuffed.
