### ISSUE TITLE
example page tree leads to 404-error

### ISSUE THREAD

**Issue by medarob** [aimeos/aimeos-typo3#177]
I wanted to download the example aimeos page tree (https://github.com/aimeos/aimeos-typo3#page-setup) but the link leads to a 404-error.

![grafik](https://user-images.githubusercontent.com/33951787/138061515-51d8d569-9785-42b8-94dc-1de3c851d62c.png)

https://aimeos.org/fileadmin/download/Aimeos-pages_21.10.t3d

**Comment by aimeos** [comment]
That was a naming mistake, now it works.
Thanks for the hint!
