### ISSUE TITLE
Can't add target attribute to links in product description

### ISSUE THREAD

**Issue by loeffe1** [aimeos/aimeos-typo3#181]
An option to select the target (this page, new page) when editing the link would be best for editors but at least let us add a target in source view...

**Comment by aimeos** [comment]
Can you please be more elaborate about what you mean? Is it related to the `Target` fields in the product and catalog panel?

**Comment by loeffe1** [comment]
Sorry for the late reply.
I am talking about the link wizard in the richtext editor for product descriptions:
https://imgur.com/R30oWUM

**Comment by aimeos** [comment]
You can customize the link feature in CKEditor 5 according to your needs:
https://ckeditor.com/docs/ckeditor5/latest/features/link.html
