### ISSUE TITLE
Your Composer dependencies require a PHP version ">= 8.0.0".

### ISSUE THREAD

**Issue by guelzow** [aimeos/aimeos-typo3#185]
Hi everyone.

In the TER version the generated composer autoloader does a PHP version check.
When a version lower than 8.0.0 is used the platform check triggers an error.

Tobi

**Comment by aimeos** [comment]
Seems like that sneaked in somehow when using composer 2.3.
We will see how we can get around that and release a new version also supporting PHP 7.4

**Comment by aimeos** [comment]
New version (22.4.2) fixes the problem
