### ISSUE TITLE
client/html/common/content/baseurl should be set to absRefPrefix if not manually defined

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#19]
client/html/common/content/baseurl  should be set to the absRefPrefix (plus uploads/tx_aimeos) it it isn't defined manually.
That way images will be displayed without the need to define baseURL.

One can define it manually, of course, but with 7.6 here is the auto option for absRefPrefix which tries to find the correct absRefPrefix automatically.

**Comment by aimeos** [comment]
Can absRefPrefix be added here?
https://github.com/aimeos/aimeos-typo3/blob/master/Configuration/TypoScript/setup.txt#L25

**Comment by AndreasA** [comment]
Only if you add support for stdWrap (cObject) there, because then one could add absRefPrefix as data by accessing TSFE:absRefPrefix

**Comment by aimeos** [comment]
We are no TYPO3 TypoScript pros and personally, TypoScript stretches my mind too much ;-)
Can you care about that so it will work like you've suggested?

**Comment by AndreasA** [comment]
TypoScript stretches everyone's mind :)
I am happy that with fluid_styled_content etc. it isn't much required anymore.

It is nice in regards to configuration options though.

This will probably not only be a TypoScript change. I can make it so though that the variable for content.baseUrl will support data in it to retrieve the absRefPrefix.
If that is OK with you I will see if I can get it to work this way :)

Or maybe even stdWrap but I think just support for data would be enough.

**Comment by aimeos** [comment]
If it's an elegant solution that works, I'm OK with it :-)

**Comment by AndreasA** [comment]
I will create a PR and we can then discuss how elegant it is.
Maybe there are better solutions :)

**Comment by aimeos** [comment]
Any news on this?

**Comment by AndreasA** [comment]
As mentioned in another ticket. I was kinda busy until now. I think I would take a look at this at the same time as the other issue.

**Comment by AndreasA** [comment]
Still now sure if the best solution here is actually to add data insert for this value only.
Or if we should initialize the value with absRefPrefix if it isn't set manually.
Best solution would probably be to allow data inserts for all aimeos values but that is probably unnecessary complex in most cases.

I think the initialization with absRefPrefix if it isn't set manually might be the best solution.

**Comment by aimeos** [comment]
If it works, we are OK with that :-)

**Comment by AndreasA** [comment]
Sorry for the delay. Completely forgot about it and iI am on skiing holiday now.
Will re-tackle the issue afterward. I think I will go with the default option but will try both and decide afterwards.

**Comment by aimeos** [comment]
The improvement would only be very small because the default value doesn't have to be changed in 99%
