### ISSUE TITLE
Aimeos Shop advanced scheduler not saving catalog page id

### ISSUE THREAD

**Issue by dabis-eu** [aimeos/aimeos-typo3#190]
Hi,

when setting up the scheduler tasks in typo3 i can't seem to get the catalog page id saved and therefore get the following error when trying to execute the scheduler:

Core: Error handler (BE): PHP Warning: Undefined property: Aimeos\Aimeos\Scheduler\Task\Email6::$aimeos_pageid_catalog in D:\xampp\htdocs\web_shop\public\typo3conf\ext\aimeos\Classes\Scheduler\Provider\Email.php line 112

I found an old issue online stating that this happens rarely, and saving the task again should fix it, but i just won't save that one field...

**Comment by aimeos** [comment]
Which PHP version do you use?

**Comment by dabis-eu** [comment]
I'm using PHP 8.1.4 and Aimeos 22.7.1

Unfortunately that's all i got so far

**Comment by aimeos** [comment]
What's your TYPO3 version?

**Comment by dabis-eu** [comment]
11.5.14

**Comment by aimeos** [comment]
Did you try to update to the latest versions (PHP and TYPO3)?

Can you try to debug these lines, especially what `$task` contains?
https://github.com/aimeos/aimeos-typo3/blob/master/Classes/Scheduler/Provider/Email.php#L111-L113

We've tried ourselves but were unable to reproduce the issue.

**Comment by dabis-eu** [comment]
Hi thanks for checking back!
Unfortunately updating didnt solve the issue...
Weirdly enough there is no warning or error when saving the task, but when trying to run the task or going back to edit it the page id of catalog is missing and an error is thrown, at this point $task contains:

object(Aimeos\Aimeos\Scheduler\Task\Email6)#1134 (29) { ["scheduler":protected]=> NULL ["taskUid":protected]=> int(8) ["disabled":protected]=> bool(false) ["runOnNextCronJob":protected]=> bool(false) ["execution":protected]=> object(TYPO3\CMS\Scheduler\Execution)#1135 (6) { ["start":protected]=> int(1661955368) ["end":protected]=> string(1) "0" ["interval":protected]=> int(60) ["multiple":protected]=> string(1) "1" ["cronCmd":protected]=> string(0) "" ["isNewSingleExecution":protected]=> bool(false) } ["executionTime":protected]=> int(1662707648) ["description":protected]=> string(0) "" ["taskGroup":protected]=> int(0) ["logger":protected]=> NULL ["fieldSite":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(15) "aimeos_sitecode" ["fieldTSconfig":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(13) "aimeos_config" ["fieldController":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(17) "aimeos_controller" ["fieldSenderFrom":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(18) "aimeos_sender_from" ["fieldSenderEmail":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(19) "aimeos_sender_email" ["fieldReplyEmail":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(18) "aimeos_reply_email" ["fieldPageLogin":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(19) "aimeos_pageid_login" ["fieldPageDetail":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(20) "aimeos_pageid_detail" ["fieldPageDownload":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(22) "aimeos_pageid_download" ["fieldTemplateBaseurl":"Aimeos\Aimeos\Scheduler\Task\Email6":private]=> string(23) "aimeos_template_baseurl" ["aimeos_sitecode"]=> array(1) { [0]=> string(7) "default" } ["aimeos_controller"]=> array(5) { [0]=> string(22) "customer/email/account" [1]=> string(24) "order/cleanup/unfinished" [2]=> string(20) "order/cleanup/unpaid" [3]=> string(20) "order/email/delivery" [4]=> string(19) "order/email/payment" } ["aimeos_config"]=> string(0) "" ["aimeos_sender_from"]=> string(17) "Mutters Treasures" ["aimeos_sender_email"]=> string(24) "shop@xxx.com" ["aimeos_reply_email"]=> string(25) "xxx@gmail.com" ["aimeos_pageid_detail"]=> string(2) "15" ["aimeos_pageid_login"]=> string(1) "5" ["aimeos_pageid_download"]=> string(1) "6" ["aimeos_template_baseurl"]=> string(52) "typo3conf/ext/aimeos/Resources/Public/Themes/default" }

**Comment by aimeos** [comment]
Did you upgrade from an older Aimeos version?

If yes, the old serialized task objects may miss new properties which can lead to that error. We've added checks to avoid that:
https://github.com/aimeos/aimeos-typo3/commit/c169e584b10183304dc6d85d4b2a2a83dff7cf1f

You can try yourself if it works now by updating to aimeos/aimeos-typo3:2022.07.x-dev
