### ISSUE TITLE
Aimeos Advanced Scheduler - Forgot field 'aimeos_pageid_catalog'

### ISSUE THREAD

**Issue by nollm** [aimeos/aimeos-typo3#191]
In the Aimeos Advanced Scheduler you forgot to save the field **aimeos_pageid_catalog** here https://github.com/aimeos/aimeos-typo3/blob/master/Classes/Scheduler/Provider/Email.php#L217
Also you forgot it in the execute function https://github.com/aimeos/aimeos-typo3/blob/master/Classes/Scheduler/Task/Email6.php#L42

**Comment by aimeos** [comment]
Sad but true. Can you check if it's now working correctly?
https://github.com/aimeos/aimeos-typo3/commit/3cef8017a52c09f199c80050be4ae2102cac909a
