### ISSUE TITLE
config.additionalHeaders as string is deprecated with 7.6 (removed with 8)

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#20]
The additionalHeaders string is deprecated with 7.6 it should be an array with numeric indices now.

However, 6.2 still requires it as string but I think the aimeos-typo3 master / 2017 version can be moved to 7.6 only anyway.

However, if backwards compatibilty is wanted, it is possible to use compatVersion TypoScript condition.

**Comment by aimeos** [comment]
TYPO3 6.2 LTS is supported at least since mid of next year I think so we should keep support in the Aimeos 2017 series. Will 8.x remove support for the string parameter in additionalHeaders()?

**Comment by AndreasA** [comment]
It has already been removed in current master:
https://git.typo3.org/Packages/TYPO3.CMS.git/commit/9603c4f3d8bbecee6c7a49892434d4ef84ec53c9

So for 8.x the check is already required.

**Comment by aimeos** [comment]
I think I've thought in the wrong direction. Where is the TS statement config.additionalHeaders is used?

**Comment by AndreasA** [comment]
https://github.com/aimeos/aimeos-typo3/blob/master/Configuration/TypoScript/setup.txt#L90

aimeosJson and aimeosPlain.

simple TypoScript condition should fix it though.

**Comment by aimeos** [comment]
Ah, I see. Can you create a PR adding the TS condition?

**Comment by AndreasA** [comment]
Just to let you know. I will tackle this and the other bug sometime in December. 
Was not able to find the time prior. Need to finish something else first.

**Comment by aimeos** [comment]
Fixed in dev-master
