### ISSUE TITLE
Update Script Composer.php has wrong path

### ISSUE THREAD

**Issue by theorak** [aimeos/aimeos-typo3#203]
On line 41 in the Update Script the path to the html themes package is defined as
'/client/html/themes'
this is wrong, should be 
'/themes/client/html'
as this has always been the correct path in the package:
https://github.com/aimeos/ai-client-html/tree/master/themes/client/html

Needs to be corrected for the Update Script to work. Currently fails with an error like "copy(): Write of 2169 bytes failed with errno=14 Bad address" on line 68

**Comment by jurrack** [comment]
+1

**Comment by aimeos** [comment]
Can you create a PR with the necessary change?

**Comment by theorak** [comment]
If you can give me a few days, I'll put that in.

**Comment by aimeos** [comment]
done
