### ISSUE TITLE
Typo3 12.4.5 - Bootstrap autoload causes error in backend module

### ISSUE THREAD

**Issue by floriankuehl** [aimeos/aimeos-typo3#204]
The error occurs when i am trying to open the Aimeos Module in Backend.

PHP Warning: file_exists(): open_basedir restriction in effect. File(/opt/plesk/php/8.2/share/pear/TYPO3/CMS/Fluid/ViewHelpers/LayoutViewHelper.php) is not within the allowed path(s): (/var/www/vhosts/###MYHOST###/:/tmp/) in /var/www/vhosts/###MYHOST###/###MYDOMAIN###/typo3-shop/vendor/aimeos/aimeos-core/Bootstrap.php line 88

I installed the Typo3 integration with the composer and executed the setup script.

**Comment by aimeos** [comment]
PHP open_basedir setting is misconfigured and also not supported. Deactivate it in your hosting admin panel.

**Comment by floriankuehl** [comment]
open_basedir has been set to "none" and now it works as expected. Thanks a lot!

**Comment by floriankuehl** [comment]
open_basedir has been set to "none" and now it works as expected. Thanks a lot!
