### ISSUE TITLE
A Warning is showing up in Database Upgrade Wizard / Reports module after successful database migration

### ISSUE THREAD

**Issue by rubensutter** [aimeos/aimeos-typo3#206]
Version 23.10.1 (https://github.com/aimeos/aimeos-typo3/releases/tag/23.10.1) 
installed via Extension Manager / TYPO3 Version 12.4.7 seems to work but shows a warning "Aktualisierung nicht vollständig" 
due to Aimeos database migration in the Upgrade Wizard. The Wizard does not show any warnings during the Aimeos database migration and states that all actions were performed successfully.

The "Analyze Database" tool shows "Database schema is up to date. Good job!". 
But still a warning in the "Reports" module remains, it looks like the Update "Done" flag isn't set correctly
after performing the Aimeos database migration using the BE Upgrade Wizard.

I get the same result after completely removing the extension, cleaning up the DB and doing a clean install via Extension Manager.

The Backend of the extension doesn't show any strange behaviour or issues and changes result in 
"Info Eintrag erfolgreich gespeichert" (successful)

**Comment by aimeos** [comment]
It's a well known problem that TYPO3 shows that warning because Aimeos update wizard can't set the flag due to missing knowledge if there's something to do or not. Unfortunately, there seems to be no solution for that in TYPO3.
