### ISSUE TITLE
Cannot install `v23.10.1` in PHP 8.2 due to `nyholm/psr7 `

### ISSUE THREAD

**Issue by rintisch** [aimeos/aimeos-typo3#207]
When trying to install v23.10.1 with TYPO3 v12 and PHP 8.2 it throws the error that this is not possible due to the dependency [nyholm/psr7](https://packagist.org/packages/nyholm/psr7) which requires php: >=7.2

Composer throws:
```
Problem 1
    - nyholm/psr7-server 1.0.0 requires php ^7.1 -> your php version (8.1; overridden via config.platform, actual: 8.2.11) does not satisfy that requirement.
    - nyholm/psr7-server[1.0.1, ..., 1.0.2] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - aimeos/aimeos-typo3 23.10.1 requires nyholm/psr7-server ^1.0 -> satisfiable by nyholm/psr7-server[1.0.0, 1.0.1, 1.0.2].
    - Root composer.json requires aimeos/aimeos-typo3 23.10.1 -> satisfiable by aimeos/aimeos-typo3[23.10.1].
```

Do I miss something?

**Comment by aimeos** [comment]
Can you try `composer up -W`?

**Comment by rintisch** [comment]
I tried `composer req aimeos/aimeos-typo3 -w` and that worked. But how does this work that it now gets installed although the PHP version is too new for this packages? (This is quite off-topic of course.)

Thanks! Now I can give aimeos a try :)

**Comment by aimeos** [comment]
`-W` means "upgrade dependencies too". The reason why it works is because there's one package that must be downgraded so all dependencies are fulfilled. The error message of composer is a bit misleading.
