### ISSUE TITLE
Incompatibility with Symfony/Console^7 (^TYPO3 12.4.10)

### ISSUE THREAD

**Issue by kmzeitgleich** [aimeos/aimeos-typo3#208]
The Commands are no longer compatible With Sympfony Console Version 7 and onwards

Example:

aimeos-type/Classes/Command/JobCommand.php

protected function execute(InputInterface $input, OutputInterface $output)

in the Symfony command this was changed to
protected function execute(InputInterface $input, OutputInterface $output): int

Why is it important?
Because TYPO3 until Version v12.4.9 has requirement
symfony/console: ^6.4

TYPO3 after Version v12.4.10 then changes to
symfony/console: ^6.4 || ^7.0
And this will in many cases break the entire installation, as this Error seemingly cannot be ignore by error handling Settings within TYPO3

How to fix:
Change the 2 Commands, works

**Comment by aimeos** [comment]
Fixed and new version is released.
