### ISSUE TITLE
Usage of anonymous function in ext_localconf.php leads to memoryleak in SystemBackendModule

### ISSUE THREAD

**Issue by yodaXX** [aimeos/aimeos-typo3#210]
The registration of
`if (!isset($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['clearCachePostProc']['aimeos'] ) ) {
    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['clearCachePostProc']['aimeos'] = function(array $cacheType, $dataHandler ) {
        \Aimeos\Aimeos\Base::clearCache($cacheType );
    };
}`
in ext_localconf.php is causing a memoryleak in Typo3 v12 BackendModule System->Configuration when viewing TYPO3_CONF_VARS

The tree view in this backendmodule doesn't handle anonymous functions in current typo3 versions.

**Comment by aimeos** [comment]
Thank you very much for spotting that!
Are there any alternatives to a closure that work?

**Comment by yodaXX** [comment]
just assign the function directly
`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['clearCachePostProc']['aimeos'] = \Aimeos\Aimeos\Base::class . '->clearCache';`

**Comment by aimeos** [comment]
OK, can you create a pull request with the necessary change?

**Comment by yodaXX** [comment]
#211
made a pull request to resolve the main issue

**Comment by aimeos** [comment]
It's merged now, available in dev-master and 2023.10.x-dev. We will release a new version of the Aimeos extension for TYPO3 this week.

Thanks a lot for your help, we appreciate it very much! :-)
