### ISSUE TITLE
Upgrade Wizard overwrites existing extension configuration

### ISSUE THREAD

**Issue by DanielSiepmann** [aimeos/aimeos-typo3#213]
We run `upgrade:run` on every deployment. That will always trigger the provided upgrade wizard `Setup`. That's fine. The actual issue is the code within the wizard:

```php 
$extconf->set('aimeos', ['useDemoData' => '']);
```
This code does replace the whole extension configuration, not only the `useDemoData` setting. The behaviour seems to be broken since TYPO3 v11 support of EXT:aimeos.

TYPO3 allowed to set individual options prior v11. Since v11 only full configuration is supported via API.

**Comment by aimeos** [comment]
Thanks for the hint and providing a PR. It has been merged now and your PR will be backported and available in the next release.

**Comment by DanielSiepmann** [comment]
Thanks for the fast response :)
