### ISSUE TITLE
ContentSecutiryPolicy for Deepl

### ISSUE THREAD

**Issue by Q4U-mspitz** [aimeos/aimeos-typo3#218]
**Environment**
1. Version 2024.04
2. Integration in TYPO3 v12, Plugin v24.4.2
3. System Linux
4. composer installation

**Describe the bug**
I try to bring deepl to work inside typo3-integration of aimeos. If i fix it with the first possible solution of https://github.com/aimeos/ai-admin-jqadm/issues/296 i ran into the next problem:
The browser blocks the access to deepl because the domain is not listet inside the default-src of the Content-Security-Policy.

**To Reproduce**
1. Edit a product
2. Edit a product-text
3. Click on "Translate" and choose a language
5. See error in browser-console

**possible solution**
If i add the deepl-domain to the CSP-Header in file Resources/Private/Layouts/Jqadm.html it does work for me.
Line 7 of Resources/Private/Layouts/Jqadm.html:
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: blob: https://*.deepl.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net ......
I don´t need to add it to Configuration/ContentSecurityPolicies.php but maybe it´s also a good idea.

**Comment by aimeos** [comment]
OK, that's an easy fix. Can you create a PR and add deepl.com there?

**Comment by aimeos** [comment]
Thanks for the PR! We've added your change to the dev-master and 2024.07 branch and optimized it a bit
