### ISSUE TITLE
[QUESTION] regenerate preview images?

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#22]
Hi,

I would like to know if it is possible to regenerate the preview images, if I change their sizes?
e.g. a scheduler task or similar? 

If not, that might be a good idea.

**Comment by aimeos** [comment]
The Aimeos components doesn't care about image sizes. But a scheduler task could be helpful, even if it's only available for TYPO3. At the moment, it's not a priority for us.

**Comment by aimeos** [comment]
We've implemented a job controller for rescaling the images in dev-master:
https://github.com/aimeos/ai-controller-jobs/blob/master/controller/jobs/src/Controller/Jobs/Media/Scale/Standard.php

The image sizes have to be configured via:
- controller/common/media/standard/preview/maxwidth
- controller/common/media/standard/preview/maxheight

**Comment by AndreasA** [comment]
Great thanks.
