### ISSUE TITLE
Aimeos is unable to retreive logged in user groups (BE or FE)

### ISSUE THREAD

**Issue by Physikbuddha** [aimeos/aimeos-typo3#224]
`aimeos/aimeos-typo3/Classes/Base/View.php` is unable to retreive the user groups from the logged in user, because it passes invalid aspect property names to the TYPO3 Context API.

The[ affected lines are 96 and 97](https://github.com/aimeos/aimeos-typo3/blob/bcb6a2e15a86d8d23e4d11ff14e24364ae05f55a/Classes/Base/View.php#L96C1-L97C97):

```php
$ids = $t3context->getPropertyFromAspect('backend.user', 'getGroupIds', []);
$names = $t3context->getPropertyFromAspect('backend.user', 'getGroupNames', []);
```

The correct property names are `groupIds` and `groupNames` instead. Calling either `getGroupIds` or `getGroupNames` will result in a `AspectPropertyNotFoundException`.

The same applies to lines 104 and 105 (frontend context).

Please see the [TYPO3 documentation on the Context API](https://docs.typo3.org/m/typo3/reference-coreapi/13.4/en-us/ApiOverview/Context/Index.html#user-aspect) for reference.

**Comment by aimeos** [comment]
Thanks a lot! The lines are changed in dev-master and 2024.10.x-dev now and will be part of the next 24.10.2 release

**Comment by Physikbuddha** [comment]
Thank you for the quick fix.

However, opening any frontend page now gives a different error:
`array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements`

Reason is that the `groupIds` array contains two more elements than the `groupNames` array, either `0, -2` if logged in or `0, -1` if logged out. Please see the [TYPO3 source repository](https://git.typo3.org/typo3/typo3/-/blame/main/typo3/sysext/core/Classes/Context/UserAspect.php?ref_type=heads#L136) for more details.

You might want to strip out all group IDs <= 0 before combining the arrays to get rid of that error.

![2024-11-08 15_25_56-TYPO3 Exception](https://github.com/user-attachments/assets/4f02e570-9261-4981-bed8-4638c40b8b55)

**Comment by Physikbuddha** [comment]
```php
$ids = array_filter($ids, fn ($id) => $id > 0);
```

**Comment by aimeos** [comment]
Thanks, we've integrated your change. Can you please test again?

**Comment by Physikbuddha** [comment]
The error is gone and the frontend is working again. Thank you!
