### ISSUE TITLE
Cannot open Aimeos backend with latest DEV version

### ISSUE THREAD

**Issue by Physikbuddha** [aimeos/aimeos-typo3#225]
I've just upgraded `aimeos/aimeos-typo3 (24.10.1 => 2024.10.x-dev)` to get the latest bugfix of https://github.com/aimeos/aimeos-typo3/issues/224. However, trying to access the Aimeos Shop module in the TYPO3 backend results in an error:

`Call to undefined method TYPO3\CMS\Backend\Routing\RouteResult::getPageId()`

I am using TYPO3 v12.4.22.
The error is probably related to this commit from last week: https://github.com/aimeos/aimeos-typo3/commit/9565aefcd3fe7edfd7dfd4dbcbdf89a9f0998442

![2024-11-08 15_15_32-TYPO3 Exception · TYPO3 CMS 12 4 22  - dokumet-ai ddev site](https://github.com/user-attachments/assets/961f17f9-69de-4e46-bcc3-1e4e0f6281b3)

**Comment by Physikbuddha** [comment]
Should be fixable by changing the affected line to
```php
$pageId = $request?->getAttribute('routing') instanceof \TYPO3\CMS\Core\Routing\PageArguments\PageArguments ? $request->getAttribute('routing')->getPageId() : 0;
```

**Comment by aimeos** [comment]
We've moved the line to frontend requests only and it seems to work now?
