### ISSUE TITLE
Undefined variable $groupIds

### ISSUE THREAD

**Issue by nollm** [aimeos/aimeos-typo3#227]
I use your extension `ai-customergroups` and get the following error.
`PHP Warning: Undefined variable $groupIds in /var/www/html/typo3/typo3conf/ext/aimeos/Classes/Base/Context.php line 343`

You have a typo there. 
https://github.com/aimeos/aimeos-typo3/blob/master/Classes/Base/Context.php#L343
It should be `$groupids` not `$groupIds`

**Comment by aimeos** [comment]
You are right, the variable is wrong. Can you create a PR to fix the problem?

**Comment by nollm** [comment]
Sure. Have created PR.

**Comment by aimeos** [comment]
Thanks, it's merged now and will be part of the next release
