### ISSUE TITLE
Scheduler task selected jobs not visible

### ISSUE THREAD

**Issue by nollm** [aimeos/aimeos-typo3#229]
I create a scheduler task, set for example the index/rebuild job and save & close.
When I reopen the task the selection is gone.

**Comment by aimeos** [comment]
Which TYPO3 and PHP version are you using?

**Comment by nollm** [comment]
Typo3 v12.4.23
PHP 8.2.24

**Comment by aimeos** [comment]
Please upgrade to Aimeos 24.10.2

**Comment by nollm** [comment]
Ah, the problem is already solved in this version. It work's. Thank you!
