### ISSUE TITLE
cHashEnforcer has to be disabled for CMS master (cHash)

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#23]
TYPO3 CMS master now checks with extbase Plugins if cHash parameter is required.
As the plugins themselves are completely uncachable cHash is not really required and isn't used by the UrlBuilder, therefore we should set:

```
features {
		requireCHashArgumentForActionArguments = 0
	}
```

for all plugins.

**Comment by aimeos** [comment]
Sure! Can you create a pull request?

**Comment by AndreasA** [comment]
Seems I have something to do the next weekend after all. Though the next weekend is Christmas so probably the one afterwards :)

**Comment by aimeos** [comment]
Has been added to dev-master. Thanks for the hint!
