### ISSUE TITLE
Error when downloading a file

### ISSUE THREAD

**Issue by nollm** [aimeos/aimeos-typo3#230]
When I want to download a file from an order in my account history I get the following error.

`InvalidTemplateResourceException: Tried resolving a template file for controller action "Default->Default" in format ".html", but none of the paths contained the expected template file (Default/Default.html). The following paths were checked: /var/www/html/my_website/typo3/sysext/fluid_styled_content/Resources/Private/Templates/, /var/www/html/my_website/typo3conf/ext/my-sitepackage/Resources/Private/Templates/ContentElements/, in file /var/www/html/typo3_src-12.4.23/vendor/typo3fluid/fluid/src/View/TemplatePaths.php:617`

It is strange that it looks in the ContentElements template folder of my sitepackage.

This is the URL to the download.
https://127.0.0.1/your-shop/my-account/download?ai[action]=download&ai[controller]=Account&ai[dl_id]=1234

**Comment by nollm** [comment]
The problem still exists. Have you been able to take a look at the problem?

**Comment by aimeos** [comment]
Not yet and we are not sure why that error pops up now

**Comment by aimeos** [comment]
We've found the problem. The TypoScript of the page is still the old one and needs to be replaced by:
```
page = PAGE
page {
    typeNum = 0
    headerData >
    config {
        disableAllHeaderCode = 1
        disableCharsetHeader = 1
        disablePrefixComment = 1
    }
    10 = CONTENT
    10 {
        table = tt_content
        select.orderBy = sorting
        select.languageField = sys_language_uid
        renderObj =< tt_content
        renderObj {
            list.templateRootPaths.5 = EXT:aimeos/Resources/Private/Templates/Fluid
        }
    }
}
```

**Comment by nollm** [comment]
On which pages I have to add the TypoScript?
I tried it on the download page but that doesn't work.

**Comment by aimeos** [comment]
Yes, on the download page and in our setup, then the download worked perfectly.

**Comment by nollm** [comment]
It only works when I clear the page before `page >`. Otherwise TypoScript from other extensions is in the `page` object.

But I got a 401 response when I open the download link.

![401](https://github.com/user-attachments/assets/605aee57-74f7-4c1d-9071-bfe674a4df9b)

**Comment by aimeos** [comment]
You have to be logged in to download the file and login is required for the page in the default page tree

**Comment by nollm** [comment]
Sorry. While testing I disabled my custom aimeos extension and forgot to include the aimeos static template.
Work now, thanks!
