### ISSUE TITLE
Migration of ai-customergroups not working

### ISSUE THREAD

**Issue by nollm** [aimeos/aimeos-typo3#231]
I executed the upgrade wizard with the ai-customergroups extension enabled.
The groups where not migrated.
Restrictions in 'Customers/Groups' of products before the migration are missing after.
No error occured during the migration.

Typo3 v12.4.23
PHP 8.2.24
Aimeos 24.10.2
ai-customergroups 24.10.2

**Comment by nollm** [comment]
It seems that you are assuming that the `domain` column contains either 'customer' or 'group'.
Not both as you can see in my screenshot.

![customer_group](https://github.com/user-attachments/assets/ca454539-194f-4834-b54b-b5d8ff778a5e)

The `parentid` in the screenshot points to the correct product and in the `mshop_product` table there is also a 1 in the `cgroups` column.

**Comment by aimeos** [comment]
This is the wrong setup task. Please have a look at `ListsMigrateDomain.php`

**Comment by aimeos** [comment]
You need the latest version of ai-customergroups extension (2024.10.5)

**Comment by nollm** [comment]
Ah ok, I thought the version must be the same like the installed aimeos version.
With ai-customergroups 24.10.5 the migration works.
But the problem still exists.
No group in the backend is shown.

![group](https://github.com/user-attachments/assets/b0f9c24e-0878-4242-ada3-bba937c6fb6b)

**Comment by aimeos** [comment]
Can you please execute `composer req aimeoscom/ai-customergroups:2024.10.x-dev` and run the setup tasks again? The `key` column wasn't migrated correctly.

**Comment by nollm** [comment]
No, it's still empty in the backend.
And the domain in `mshop_product_list` is `customer/group` again.

**Comment by aimeos** [comment]
Did you reset your DB to the state of your previous Aimeos version (before 2024.x)? The latest version of the ai-customergroups extension (2024.10.6) migrates the `customer/group` list record correctly.

**Comment by nollm** [comment]
Yes I resetted the database to the state of Aimeos v22.10.9.
The migration then was done with Aimeos v24.10.2 and ai-customergroups extension 2024.10.x-dev which you suggested before.
With that the column `domain` was not converted from `customer/group` to `group` like before in ai-customergroups 2024.10.5

**Comment by aimeos** [comment]
How does the relevant database records look like?

**Comment by nollm** [comment]
Before migration

![record](https://github.com/user-attachments/assets/271a4425-3c78-4517-85cc-33f5be2f35e1)

Column domain und key was not converted from `customer/group` to `group`.
I tried now ai-customergroups 2024.10.6

Another Problem is that I can only select "Administrator" and "Editor". Not my Typo3 UserGroups.

**Comment by aimeos** [comment]
Can you check why these lines in ./vendor/aimeoscom/ai-customergroups/setup/ListsMigrateDomain.php don't update the records in your database as it works perfectly in our test setup?
```
	public function up()
	{
		$this->info( 'Updating group domain in list tables', 'vv' );

		foreach( ['attribute', 'catalog', 'media', 'price', 'product', 'service', 'supplier', 'text'] as $domain )
		{
			$result = $this->db( 'db-' . $domain )->stmt()
				->select( 'id', 'type', 'refid' )
				->from( 'mshop_' . $domain . '_list' )
				->where( '"key" LIKE \'customer/group|%\'' )
				->executeQuery();

			$this->db( 'db-' . $domain, true )->transaction( function( $db ) use ( $result ) {

				while( $row = $result->fetchAssociative() )
				{
					$db->update(
						'mshop_' . $domain . '_list',
						['domain' => 'group', 'key' => 'group|' . $row['type'] . '|' . $row['refid']],
						['id' => $row['id']]
					);
				}
			} )->close();
		}
```

**Comment by nollm** [comment]
When I call the SQL for `mshop_product_list` on this spot I get false.

![code](https://github.com/user-attachments/assets/c5784b77-b43e-4f37-a5b8-d8c1b299b897)

**Comment by nollm** [comment]
Is it because of the double quotes around "key" ?
I use MariaDB and there you use back ticks ( ` ).

**Comment by aimeos** [comment]
Changed. Can you please update (2024.10.x-dev) and test again?

**Comment by nollm** [comment]
You forgot the `$domain` in the `use`.
`$domain` is otherwise not accessible in function.

```diff
+ $this->db( 'db-' . $domain, true )->transaction( function( $db ) use ( $result ) {
- $this->db( 'db-' . $domain, true )->transaction( function( $db ) use ( $result, $domain ) {
```

**Comment by aimeos** [comment]
Done

**Comment by nollm** [comment]
Now both columns are converted.

But the backend is still empty.
Maybe because of this.
> Another Problem is that I can only select "Administrator" and "Editor" in the backend. Not my Typo3 UserGroups.

**Comment by aimeos** [comment]
Is the page ID for the fe_groups configured correctly to the right sysfolder and contain the records in the fe_groups table the sysfolder page iD?

https://aimeos.org/docs/2024.x/config/mshop/manager-typo3/#pid-default

**Comment by aimeos** [comment]
> Contain the records in the fe_groups table the sysfolder page iD?

Guess, this is not the case because your TypoScript configuration only works for frontend plugins, not for backend modules. You can either add the configuration to the `mshop.php` configuration file in your custom Aimeos extension (recommended) or you have to add `module.tx_aimeos.settings.mshop.customer.manager.typo3.pid-default` for the backend and `mshop.customer.manager.typo3.pid-default` in each relevant scheduler task.

**Comment by nollm** [comment]
I tried your recommended solution. Still no groups in the backend.

![mshop_php](https://github.com/user-attachments/assets/7784649d-e206-439f-bb2b-70070f4e4ea5)

**Comment by aimeos** [comment]
How does the records in your fe_groups table look like?

**Comment by nollm** [comment]
![fe_groups](https://github.com/user-attachments/assets/89fa3449-e804-4663-8853-5ce73585ef40)

**Comment by aimeos** [comment]
Are the "admin" and "editor" records in any way different?

**Comment by nollm** [comment]
When I set a breakpoint [here](https://github.com/aimeos/ai-typo3/blob/master/src/MShop/Group/Manager/Typo3.php#L92) in ai-typo3 it does not stop when I open the groups list.
Only [this](https://github.com/aimeos/aimeos-core/blob/master/src/MShop/Group/Manager/Standard.php) class is used from aimeos-core.
Is that right?

**Comment by nollm** [comment]
> Are the "admin" and "editor" records in any way different?

Yes. Both have 0 as pid.

**Comment by aimeos** [comment]
> When I set a breakpoint [here](https://github.com/aimeos/ai-typo3/blob/master/src/MShop/Group/Manager/Typo3.php#L92) in ai-typo3 it does not stop when I open the groups list. Only [this](https://github.com/aimeos/aimeos-core/blob/master/src/MShop/Group/Manager/Standard.php) class is used from aimeos-core. Is that right?

Thanks, this was the crucial hint! The default configuration now contains lines for using the correct manager:
https://github.com/aimeos/aimeos-typo3/commit/c54569c1a079a6b51a44248fa4a2fc1b00c5f3dd

**Comment by nollm** [comment]
I think the exception occurs, because in `CatalogCustomerGroup` the `checkItem()` function don't get the typo3 user groups from logged in user.
This line `$groupIds = $context->groups();` results always in an empty array.

**Comment by aimeos** [comment]
> Is there a possibility to see the code of a group instead of description? The select box is full of empty entries. !

OK, the group code is now shown if no label (description) is available.

> But I still have problems. I call a site with a category tree. There are categories with restrictions to groups. I get an exception and redirect to 404 page.

Does your user has admin privileges and no groups assigned?

**Comment by nollm** [comment]
> OK, the group code is now shown if no label (description) is available.

Thank you! Is this fix in ai-customergroups?

> Does your user has admin privileges and no groups assigned?

No, I'am logged in with a normal frontend user which have 4 groups.

![user](https://github.com/user-attachments/assets/8d691095-5eb5-44ef-88c4-b2577561d097)

**Comment by aimeos** [comment]
> > OK, the group code is now shown if no label (description) is available.
> 
> Thank you! Is this fix in ai-customergroups?

Yes

> No, I'am logged in with a normal frontend user which have 4 groups.

Can you please update to aimeos/aimeos-typo3:2024.10.x-dev? There's a fix available: https://github.com/aimeos/aimeos-typo3/commit/4a25b525acabfca2d394f6da7b7931955f415c1d

**Comment by nollm** [comment]
Now you compare IDs with names with the `array_intersect` function.

![wrong_compare](https://github.com/user-attachments/assets/3a57c8f4-8128-43cb-bb29-3342455f7e16)

And when the condition is false I think a redirect to 404 page is wrong. Or is this behaviour expected?

**Comment by nollm** [comment]
Now nothing is working anymore in the frontend.
I get for all shop content elements an error.
Here the first 10 line from stack trace.

```
Called unknown method "getResourceType" on class "Aimeos\MShop\Media\Manager\Standard"
#0 [internal function]: Aimeos\MShop\Media\Manager\Standard->__call('getResourceType', Array)
#1 /var/www/html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/src/MShop/Common/Manager/Decorator/Base.php(50): call_user_func_array(Array, Array)
#2 /var/www/html/typo3/typo3conf/ext/aimeos_ext/Resources/Private/Extensions/ai-customergroups/src/MShop/Common/Manager/Decorator/CustomerGroup.php(63): Aimeos\MShop\Common\Manager\Decorator\Base->__call('getResourceType', Array)
#3 /var/www/html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/src/MShop/Common/Manager/Decorator/Depth.php(58): Aimeos\MShop\Common\Manager\Decorator\CustomerGroup->search(Object(Aimeos\Base\Criteria\SQL), Array, NULL)
#4 /var/www/html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/src/MShop/Common/Manager/Decorator/Lazy.php(38): Aimeos\MShop\Common\Manager\Decorator\Depth->search(Object(Aimeos\Base\Criteria\SQL), Array, NULL)
#5 /var/www/html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/map/src/Map.php(5679): Aimeos\MShop\Common\Manager\Decorator\Lazy->Aimeos\MShop\Common\Manager\Decorator\closure()
#6 /var/www/html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/map/src/Map.php(5742): Aimeos\Map->array(Object(Closure))
#7 /var/www/html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/map/src/Map.php(3078): Aimeos\Map->list()
#8 /var/www/html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/src/MShop/Common/Manager/Lists/Base.php(173): Aimeos\Map->offsetExists('3653')
#9 /var/www/html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/src/MShop/Common/Manager/Decorator/Depth.php(58): Aimeos\MShop\Common\Manager\Lists\Base->search(Object(Aimeos\Base\Criteria\SQL), Array, NULL)
#10 /var/www/html/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/src/MShop/Common/Manager/Decorator/Lazy.php(38): Aimeos\MShop\Common\Manager\Decorator\Depth->search(Object(Aimeos\Base\Criteria\SQL), Array, NULL)
```

**Comment by aimeos** [comment]
The change from dev-master has been merged into 2024.10.x-dev. Can you please try again?

**Comment by nollm** [comment]
Now it is working. Thank you very much!

The entries in the select box have all a name now.
But when I select and save a group, the text disappear.
Also when I reopen the product the text is missing.

**Comment by aimeos** [comment]
The ai-customergroups extension version 2024.10.x-dev contains now improvements for customers or groups with empty labels/descriptions

**Comment by nollm** [comment]
Yes that looks good.
Thank you for all this support!

**Comment by nollm** [comment]
Sorry but I have to reopen this issue again.
With the 2024.10.x-dev version of Aimeos and ai-customergroups I run again in this issue.

![category_404](https://github.com/user-attachments/assets/102366ec-0db9-43a1-a941-bae24e34d629)

**Comment by aimeos** [comment]
There have been no change made regarding this up to now. The most important info would be if categories are displayed which shouln't be available for your user and why because the ./vendor/aimeoscom/ai-customergroups/src/MShop/Catalog/Manager/Decorator/CatalogCustomerGroup.php class adds a filter to remove the items from the tree if they are not available (provided you've configured it for the frontend).

**Comment by nollm** [comment]
> Now you compare IDs with names with the `array_intersect` function.
> 
> ![wrong_compare](https://private-user-images.githubusercontent.com/42864489/390437770-3a57c8f4-8128-43cb-bb29-3342455f7e16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDgzNTIsIm5iZiI6MTczMjgwODA1MiwicGF0aCI6Ii80Mjg2NDQ4OS8zOTA0Mzc3NzAtM2E1N2M4ZjQtODEyOC00M2NiLWJiMjktMzM0MjQ1NWY3ZTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE1MzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZjU0M2MzZGJiNDc5ZjI2ZWMyNDg0ZDJjMGJmNzU2YWYzMGQxMDI4MWUyMDZkYTE5ODBhMjkxMzUxNmNmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FG47UoUuo4LQuggDqDlHbxPqhekNTnN2fEUmzLQ0xAg)
> 
> And when the condition is false I think a redirect to 404 page is wrong. Or is this behaviour expected?

I have again this problem.

**Comment by aimeos** [comment]
This commit should have fixed the problem: https://github.com/aimeos/aimeos-typo3/commit/430ec327396c8228990dd51916906880f5e76310

**Comment by nollm** [comment]
You're right. I cloned the aimeos-typo3 repo and executed phing deploy. Is the change not in there?

**Comment by aimeos** [comment]
The change is in master and 2024.10 branches. If you've used `git clone`, use `git pull` to get updates

**Comment by nollm** [comment]
Sorry, my fault. I forgot that the change was made in the aimeos-typo3 repo and not in a composer dependency.
Thank you!
