### ISSUE TITLE
Absolute URLs in CSV import

### ISSUE THREAD

**Issue by nollm** [aimeos/aimeos-typo3#232]
Is it not possible anymore to use absolute URLs in the CSV import?

`plugin.tx_aimeos.settings.controller.jobs.product.import.csv.location`
`plugin.tx_aimeos.settings.controller.jobs.product.import.csv.backup`

**Comment by aimeos** [comment]
No, because this doesn't work if you have testing/staging/production environments. The paths must be relative to the `fs-import` virtual file system defined by default in the Aimeos configuration.
