### ISSUE TITLE
Error messages in basket popup cut off

### ISSUE THREAD

**Issue by nollm** [aimeos/aimeos-typo3#234]
When I click on "Add to basket" the basket popup is shown.
Everything outside of the `<div>` container will be cut off (maybe from Typo3).
That is a problem when an exception occurs and the exception decorator creates the error list before the basket popup content.
You can try this when you add [here](https://github.com/aimeos/ai-client-html/blob/master/templates/client/html/basket/standard/body.php#L14) this line `<p>Outside</p>` 
You will not see the text 'Outside' in the basket pupup.

![basket_popup](https://github.com/user-attachments/assets/0875b9fb-d34b-4913-878e-70613f1543ca)

**Comment by aimeos** [comment]
Seems like you have an old version of the aimeos.js file because in the latest version, error and info messages are added to the modal by these lines: https://github.com/aimeos/ai-client-html/blob/master/themes/client/html/default/aimeos.js#L215-L217

**Comment by nollm** [comment]
That was the problem. Thank you for the hint!

In the JavaScript function `updateBasket`, you mentioned above, is a call to the `jsonurl`.
When I take a look in the network tab (F12 - dev tools of browser) I get the same error like in this issue #230.

**Comment by aimeos** [comment]
If you are upgrading from a previous version, please make sure your TypoScript for the jsonapi and download page are up to date: https://github.com/aimeos/aimeos-typo3/blob/master/Configuration/TypoScript/setup.txt#L55-L97

**Comment by aimeos** [comment]
The correct error message is now displayed to in aimeos/ai-client-html:2024.10.x-dev

**Comment by nollm** [comment]
Perfect, it works. Thank you!
