### ISSUE TITLE
Typo3 Distribution can not be installed

### ISSUE THREAD

**Issue by kludikovsky** [aimeos/aimeos-typo3#24]
The Installation requires an older Version of bootstrap.

![_screen_shot_2016-12-22_161455](https://cloud.githubusercontent.com/assets/6077916/21430122/1762413c-c862-11e6-8960-47447c585f7d.jpg)

**Comment by aimeos** [comment]
Yes, that's still the case because all versions including 7.0.2 are buggy. They add a <div> tag around all JSON output so stock levels and autosuggest won't work

**Comment by aimeos** [comment]
The latest Aimeos distribution (17.3.0) released today supports now bootstrap_package 7.x and TYPO3 8.x
