### ISSUE TITLE
Problem: automatically sending mails with scheduler/zendramework error

### ISSUE THREAD

**Issue by Wahni69** [aimeos/aimeos-typo3#3]
Hi!
The shop is working fine, but a scheduler-task makes problems. 
If I manually start the task (Order payment related E-Mail...) I get the following error (shortend):

PHP Warning: Illegal offset type in .../typo3conf/ext/aimeos/Resources/Libraries/zendframework/zend-i18n/src/Translator/Translator.php line 441

On line 441 is the following code:
 if (isset($this->messages[$textDomain][$locale][$message])) {
            return $this->messages[$textDomain][$locale][$message];
   }
If I deactived the code, the whole shop is not translated into german, but the Scheduler-Task works. 

The same task does not start automatically. Maybe because of the mentioned error ?
 It seems that the language setting of typo3 is the problem? How can I solve it?

Best wishes
Marcus

**Comment by aimeos** [comment]
Further discussed in the forum:
http://aimeos.org/help/typo3-extension-f16/problem-with-sending-scheduled-e-mails-t444.html

**Comment by aimeos** [comment]
Problem is solved according to http://aimeos.org/help/typo3-extension-f16/problem-with-sending-scheduled-e-mails-t444-20.html
