### ISSUE TITLE
UriBuilder doesn't generate URLs

### ISSUE THREAD

**Issue by aimeos** [aimeos/aimeos-typo3#32]
There's a problem with the new constant editor, e.g. on the basket page. The flexform contains no page reference for the page itself and if no page ID in the constants is added, the UriBuilder generates no links for modifying the quantity and deleting items from the basket.

@gilbertsoft Do you know a solution for this? If not, we have to remove the page IDs from the constants editor.

**Comment by gilbertsoft** [comment]
Yes, I have already found this problem yesterday and will PR it now...

**Comment by aimeos** [comment]
@gilbertsoft As long as the empty page ID configuration in the constants section is available, no URL are generated. We've removed that now and left the constant editor for option with a default value. This works pretty well.
