### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/aimeos-typo3#37]
I'm currently working on the emails aimeos is sending and here are some questions and problems with it:

- special chars e.g. umlauts are not correctly shown, I can't find an encoding tag in the header. Compared to other html emails I have received there is always a encoding defined
- why is the css included in the body and not the header?
- no link is made on terms and conditions on the bottom

**Comment by aimeos** [comment]
- Probably adding an encoding in the header may help
- That's for maximum compatibility. Many web clients remove CSS from the head section
- You can always add a link (hard coded) to the terms section at the body if you need it

**Comment by gilbertsoft** [comment]
- Works fine with the encoding in the header. Should I make a PR on this?
- then it's fine :-)
- I thought could be a nice default feature? I don't need it.

and more:

- the language of the customer isn't correcty processed. I get the mails in english, but I set language of the customer to Swiss German. Therefore I defined a new language (de_CH) according to the iso standard. Now I see that the languageid is saved in lowercases to mshop_order_base_address, but I can't find the place in the source code where this happens. Any idea where to search?

Changing to simple "de" is not possible because it's planed to expand the sales to germany and austria and there are dialect dependent names in the products for each country. I don't think you understand "Nuggikette" or "Nuschi" or do you ;-) ? As I see your office is located in bavaria then it could be possible. I live on the other side 5 km to bavaria in Kufstein.

Not concerning the emails but the order process:
- the name of the delivery is not correctly submitted to PayPal or showed by PayPal (using paypal express). PayPal shows the code and not the name. Is that normal? I see you transmit the code and the name...

**Comment by aimeos** [comment]
Yes, we would appreciate your PR for the encoding :-)

Adding a T&C link in the translation for e-mail footer might be problematic because it's used for text and html e-mails. Therefore, this is not done by default as most shop owners don't require this.

Yeah, I think you are the first one who is using country specific languages! Personally, I only have a very rough idea what this could mean ;-)
The problem was there: https://github.com/aimeos/aimeos-core/commit/0866501d53ad87f546aa231510e132b692a66788

Changed the values sent to PayPal. Now it should display the name:
https://github.com/aimeos/aimeos-core/commit/a098c874d09cd8d7a530b44c54366ac108dd159f

**Comment by gilbertsoft** [comment]
Thanks! Didn't see that, I do not get enough sleep at the moment, too much work and the kids are sick ;-(

As I read at https://aimeos.org/docs/TYPO3/Configure_language_and_currency there's no fallback to the base language for products etc. Is this because you never needed it or is it a problem implementing that?

fyi: Schnullerkette und Mullwindel ;-)

**Comment by aimeos** [comment]
Don't worry, we will always fix potential problems as soon as possible if you name them :-)

If nothing is configured, the fallback will always be English.

The first one was clear to me but I never thought about "Mullwindel" for the second one ;-)

**Comment by gilbertsoft** [comment]
I think we are not talking about the same thing, I'm talking about this part:

> If the translation for a language variant is not available, the base language will be used, e.g. German translations would be used if the Swiss variant isn't available.
> 
> The fallback to the base language is only available for translations! Product names, descriptions and all other texts in the shop need to be available in the language variant. Otherwise, the product labels (or more generally speaking, the item labels) will be used.

I like to have a fallback for items from the db too and need your opinion about the realizability. Not urgent, but if you say this isn't a big change I'll try to do it soon...

**Comment by aimeos** [comment]
That's difficult and can only be achieved if e.g. all items for "de_CH" and "de" are retrieved and then the ones for "de" are filtered out if there's a corresponding item for "de_CH". Nothing that's done easily.

**Comment by gilbertsoft** [comment]
Ok thanks, will have a look at the corresponding code if I find the time...
