### ISSUE TITLE
Don't use no_cache param

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/aimeos-typo3#40]
I got an answer from realurl: https://github.com/dmitryd/typo3-realurl/issues/404

So the Typo3.php with the link builder access should be rewritten not longer using the no_cache option. As I know actions are already defined as not cachable as Dimitry wrote.

I will continue investigation on this issue...

**Comment by aimeos** [comment]
Aimeos doesn't use the no_cache parameter at all. The URL view helper only sets this parameter if it's configured but that's not the case for any URL according to the TS config in the setup.txt

**Comment by gilbertsoft** [comment]
That's not correct: https://github.com/aimeos/aimeos-typo3/blob/master/Configuration/TypoScript/setup.txt#L114

But after the disussion with Dimitry the should be removed, the actions are already declared as non-cachable.

**Comment by aimeos** [comment]
You are right, missed the TS-settings for the pages. Is removed now in 278d6f7

**Comment by gilbertsoft** [comment]
I'm already testing without the no_cache option, but I still get links with the no_cache=1 param. Cleared all caches 5 times, truncated various cache and realurl tables, apu, etc. I'm debugging now on the url creation...

**Comment by aimeos** [comment]
Is the `cf_aimeos` table empty?

**Comment by gilbertsoft** [comment]
tuncated too, but will try again...

**Comment by gilbertsoft** [comment]
Always 7 records in there.

**Comment by aimeos** [comment]
Are they renewed after each request? I would like to eliminate the possibility that clearing the cache don't work

**Comment by gilbertsoft** [comment]
Yes they are. On the last try I cleared all caches at be and install tool, then all cache* and cf* tables were empty. In addition I trunceted the tx_realurl* tables. But then I still get links for stock and counts with the no_cache param. All truncated tables now containing again some data

**Comment by gilbertsoft** [comment]
Finally found it: the aimeos-dist sets the no cache option on the json and text pages

**Comment by gilbertsoft** [comment]
Seems to work fine without no_cache=1 set. Setting the actions as non-cachable as done in ext_local.php is enough to prevent caching. I added the request time to the output to check if it's a cached or live result and always was a non-cached result. You can remove the no cache flag on the pages count, stock, search and update to get urls to this pages without no_cache=1 param.

**Comment by aimeos** [comment]
OK, we will update the imported page tree before the next distribution release.
The issue will stay open until it's done.

**Comment by gilbertsoft** [comment]
Perhaps you like to open a new one at the dist repo? In this repo it's done so far!

**Comment by aimeos** [comment]
Yes, that would be best. Do you care about?

**Comment by gilbertsoft** [comment]
Ok, done: https://github.com/aimeos/aimeos-typo3-dist/issues/1
