### ISSUE TITLE
Wrong additionalHeaders code in TypoScript setup.txt

### ISSUE THREAD

**Issue by vmans** [aimeos/aimeos-typo3#43]
Change
additionalHeaders.type = Content-type:application/javascript
into
additionalHeaders = Content-type:application/javascript

and
additionalHeaders.type = Content-type:text/plain
into
additionalHeaders = Content-type:text/plain

**Comment by aimeos** [comment]
In which version did you found that?

The 16.10.x LTS versions contain
```
additionalHeaders = Content-type:application/javascript
```
while in the current 17.2.x versions it's
```
additionalHeaders.10.header = Content-type:application/javascript
```
which should be correct according to
https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/#additionalheaders

**Comment by vmans** [comment]
In 17.2.0.
But now I doubt why 17.2.0 is installed since 17.2.1 is available wit the right code.
