### ISSUE TITLE
Countryname not fetched from ISO code in frontend form

### ISSUE THREAD

**Issue by vmans** [aimeos/aimeos-typo3#44]
I run 17.2.1 on TYPO3 8.6.1 (yes it works fine for most parts).

Many country 2 digit ISO are not translated into the country name. This effect starts around the KG code and then continues frequently until it remains. Therefor, NL stays NL instead of Nederland.
Even if I change the list to

plugin.tx_aimeos.settings.client.html.checkout.standard.address.countries {
     0 = NL
     # Nederland
}

I only get NL in the form select field.

This is the HTML:

`<select id="address-billing-countryid" name="ai[ca_billing][order.base.address.countryid]">

			<option value="">Selecteer land</option>
							<option value="AD">
					Andorra				</option>
							<option value="AE">
					United Arab Emirates				</option>
							<option value="AF">
					Afghanistan				</option>
							<option value="AG">
					Antigua and Barbuda				</option>
							<option value="AI">
					Anguilla				</option>
							<option value="AL">
					Albania				</option>
							<option value="AM">
					Armenia				</option>
							<option value="AO">
					Angola				</option>
							<option value="AQ">
					Antarctica				</option>
							<option value="AR">
					Argentina				</option>
							<option value="AS">
					American Samoa				</option>
							<option value="AT">
					Austria				</option>
							<option value="AU">
					Australia				</option>
							<option value="AW">
					Aruba				</option>
							<option value="AX">
					Åland Islands				</option>
							<option value="AZ">
					Azerbaijan				</option>
							<option value="BA">
					Bosnia and Herzegovina				</option>
							<option value="BB">
					Barbados				</option>
							<option value="BD">
					Bangladesh				</option>
							<option value="BE">
					Belgium				</option>
							<option value="BF">
					Burkina Faso				</option>
							<option value="BG">
					Bulgaria				</option>
							<option value="BH">
					Bahrain				</option>
							<option value="BI">
					Burundi				</option>
							<option value="BJ">
					Benin				</option>
							<option value="BL">
					Saint Barthélemy				</option>
							<option value="BM">
					Bermuda				</option>
							<option value="BN">
					Brunei Darussalam				</option>
							<option value="BO">
					Bolivia, Plurinational State of				</option>
							<option value="BQ">
					Bonaire, Sint Eustatius and Saba				</option>
							<option value="BR">
					Brazil				</option>
							<option value="BS">
					Bahamas				</option>
							<option value="BT">
					Bhutan				</option>
							<option value="BV">
					Bouvet Island				</option>
							<option value="BW">
					Botswana				</option>
							<option value="BY">
					Belarus				</option>
							<option value="BZ">
					Belize				</option>
							<option value="CA">
					Canada				</option>
							<option value="CC">
					Cocos (Keeling) Islands				</option>
							<option value="CD">
					Congo, the Democratic Republic of the				</option>
							<option value="CF">
					Central African Republic				</option>
							<option value="CG">
					Congo				</option>
							<option value="CH">
					Switzerland				</option>
							<option value="CI">
					Côte d'Ivoire				</option>
							<option value="CK">
					Cook Islands				</option>
							<option value="CL">
					Chile				</option>
							<option value="CM">
					Cameroon				</option>
							<option value="CN">
					China				</option>
							<option value="CO">
					Colombia				</option>
							<option value="CR">
					Costa Rica				</option>
							<option value="CU">
					Cuba				</option>
							<option value="CV">
					Cape Verde				</option>
							<option value="CW">
					Curaçao				</option>
							<option value="CX">
					Christmas Island				</option>
							<option value="CY">
					Cyprus				</option>
							<option value="CZ">
					Czech Republic				</option>
							<option value="DE">
					Germany				</option>
							<option value="DJ">
					Djibouti				</option>
							<option value="DK">
					Denmark				</option>
							<option value="DM">
					Dominica				</option>
							<option value="DO">
					Dominican Republic				</option>
							<option value="DZ">
					Algeria				</option>
							<option value="EC">
					Ecuador				</option>
							<option value="EE">
					Estonia				</option>
							<option value="EG">
					Egypt				</option>
							<option value="EH">
					Western Sahara				</option>
							<option value="ER">
					Eritrea				</option>
							<option value="ES">
					Spain				</option>
							<option value="ET">
					Ethiopia				</option>
							<option value="FI">
					Finland				</option>
							<option value="FJ">
					Fiji				</option>
							<option value="FK">
					Falkland Islands (Malvinas)				</option>
							<option value="FM">
					FM				</option>
							<option value="FO">
					Faroe Islands				</option>
							<option value="FR">
					France				</option>
							<option value="GA">
					Gabon				</option>
							<option value="GB">
					United Kingdom				</option>
							<option value="GD">
					Grenada				</option>
							<option value="GE">
					Georgia				</option>
							<option value="GF">
					French Guiana				</option>
							<option value="GG">
					Guernsey				</option>
							<option value="GH">
					Ghana				</option>
							<option value="GI">
					Gibraltar				</option>
							<option value="GL">
					Groenland				</option>
							<option value="GM">
					Gambia				</option>
							<option value="GN">
					Guinea				</option>
							<option value="GP">
					Guadeloupe				</option>
							<option value="GQ">
					Equatorial Guinea				</option>
							<option value="GR">
					Greece				</option>
							<option value="GS">
					South Georgia and the South Sandwich Islands				</option>
							<option value="GT">
					Guatemala				</option>
							<option value="GU">
					Guam				</option>
							<option value="GW">
					Guinea-Bissau				</option>
							<option value="GY">
					Guyana				</option>
							<option value="HK">
					Hong Kong				</option>
							<option value="HM">
					Heard Island and McDonald Islands				</option>
							<option value="HN">
					Honduras				</option>
							<option value="HR">
					Croatia				</option>
							<option value="HT">
					Haiti				</option>
							<option value="HU">
					Hungary				</option>
							<option value="ID">
					Indonesia				</option>
							<option value="IE">
					Ireland				</option>
							<option value="IL">
					Israel				</option>
							<option value="IM">
					IM				</option>
							<option value="IN">
					India				</option>
							<option value="IO">
					IO				</option>
							<option value="IQ">
					Irak				</option>
							<option value="IR">
					Iran, Islamitische republiek van				</option>
							<option value="IS">
					Ijsland				</option>
							<option value="IT">
					Italie				</option>
							<option value="JE">
					JE				</option>
							<option value="JM">
					Jamaica				</option>
							<option value="JO">
					JO				</option>
							<option value="JP">
					Japan				</option>
							<option value="KE">
					Kenia				</option>
							<option value="KG">
					KG				</option>
							<option value="KH">
					KH				</option>
							<option value="KI">
					KI				</option>
							<option value="KM">
					KM				</option>
							<option value="KN">
					KN				</option>
							<option value="KP">
					KP				</option>
							<option value="KR">
					Korea, Republiek van				</option>
							<option value="KW">
					Koeweit				</option>
							<option value="KY">
					KY				</option>
							<option value="KZ">
					Kazachstan				</option>
							<option value="LA">
					LA				</option>
							<option value="LB">
					Libanon				</option>
							<option value="LC">
					LC				</option>
							<option value="LI">
					LI				</option>
							<option value="LK">
					Sri Lanka				</option>
							<option value="LR">
					LR				</option>
							<option value="LS">
					LS				</option>
							<option value="LT">
					LT				</option>
							<option value="LU">
					Luxemburg				</option>
							<option value="LV">
					Letland				</option>
							<option value="LY">
					Libie				</option>
							<option value="MA">
					Marokko				</option>
							<option value="MC">
					Monaco				</option>
							<option value="MD">
					Moldavie, Republiek van				</option>
							<option value="ME">
					Montenegro				</option>
							<option value="MF">
					MF				</option>
							<option value="MG">
					Madagascar				</option>
							<option value="MH">
					MH				</option>
							<option value="MK">
					Macedonië				</option>
							<option value="ML">
					Mali				</option>
							<option value="MM">
					MM				</option>
							<option value="MN">
					Mongolië				</option>
							<option value="MO">
					MO				</option>
							<option value="MP">
					MP				</option>
							<option value="MQ">
					MQ				</option>
							<option value="MR">
					MR				</option>
							<option value="MS">
					MS				</option>
							<option value="MT">
					Malta				</option>
							<option value="MU">
					MU				</option>
							<option value="MV">
					MV				</option>
							<option value="MW">
					MW				</option>
							<option value="MX">
					MX				</option>
							<option value="MY">
					MY				</option>
							<option value="MZ">
					MZ				</option>
							<option value="NA">
					NA				</option>
							<option value="NC">
					NC				</option>
							<option value="NE">
					NE				</option>
							<option value="NF">
					NF				</option>
							<option value="NG">
					NG				</option>
							<option value="NI">
					NI				</option>
							<option value="NL">
					NL				</option>
							<option value="NO">
					NO				</option>
							<option value="NP">
					NP				</option>
							<option value="NR">
					Nauru				</option>
							<option value="NU">
					NU				</option>
							<option value="NZ">
					NZ				</option>
							<option value="OM">
					OM				</option>
							<option value="PA">
					PA				</option>
							<option value="PE">
					PE				</option>
							<option value="PF">
					PF				</option>
							<option value="PG">
					PG				</option>
							<option value="PH">
					PH				</option>
							<option value="PK">
					PK				</option>
							<option value="PL">
					PL				</option>
							<option value="PM">
					PM				</option>
							<option value="PN">
					PN				</option>
							<option value="PR">
					PR				</option>
							<option value="PS">
					PS				</option>
							<option value="PT">
					PT				</option>
							<option value="PW">
					PW				</option>
							<option value="PY">
					PY				</option>
							<option value="QA">
					QA				</option>
							<option value="RE">
					RE				</option>
							<option value="RO">
					RO				</option>
							<option value="RS">
					RS				</option>
							<option value="RU">
					RU				</option>
							<option value="RW">
					RW				</option>
							<option value="SA">
					SA				</option>
							<option value="SB">
					SB				</option>
							<option value="SC">
					SC				</option>
							<option value="SD">
					SD				</option>
							<option value="SE">
					SE				</option>
							<option value="SG">
					SG				</option>
							<option value="SH">
					SH				</option>
							<option value="SI">
					SI				</option>
							<option value="SJ">
					SJ				</option>
							<option value="SK">
					SK				</option>
							<option value="SL">
					SL				</option>
							<option value="SM">
					SM				</option>
							<option value="SN">
					SN				</option>
							<option value="SO">
					SO				</option>
							<option value="SR">
					SR				</option>
							<option value="SS">
					SS				</option>
							<option value="ST">
					ST				</option>
							<option value="SV">
					SV				</option>
							<option value="SX">
					SX				</option>
							<option value="SY">
					SY				</option>
							<option value="SZ">
					SZ				</option>
							<option value="TC">
					TC				</option>
							<option value="TD">
					TD				</option>
							<option value="TF">
					TF				</option>
							<option value="TG">
					TG				</option>
							<option value="TH">
					TH				</option>
							<option value="TJ">
					TJ				</option>
							<option value="TK">
					TK				</option>
							<option value="TL">
					TL				</option>
							<option value="TM">
					TM				</option>
							<option value="TN">
					TN				</option>
							<option value="TO">
					TO				</option>
							<option value="TR">
					TR				</option>
							<option value="TT">
					TT				</option>
							<option value="TV">
					TV				</option>
							<option value="TW">
					TW				</option>
							<option value="TZ">
					TZ				</option>
							<option value="UA">
					UA				</option>
							<option value="UG">
					UG				</option>
							<option value="UM">
					UM				</option>
							<option value="US">
					US				</option>
							<option value="UY">
					UY				</option>
							<option value="UZ">
					UZ				</option>
							<option value="VA">
					VA				</option>
							<option value="VC">
					VC				</option>
							<option value="VE">
					VE				</option>
							<option value="VG">
					VG				</option>
							<option value="VI">
					VI				</option>
							<option value="VN">
					VN				</option>
							<option value="VU">
					VU				</option>
							<option value="WF">
					WF				</option>
							<option value="WS">
					WS				</option>
							<option value="YE">
					YE				</option>
							<option value="YT">
					YT				</option>
							<option value="ZA">
					ZA				</option>
							<option value="ZM">
					ZM				</option>
							<option value="ZW">
					ZW				</option>
					</select>`

**Comment by aimeos** [comment]
What problems do you still have using TYPO3 8.6.1? Did you got the "&cHash empty" problem too?

The Dutch translation isn't complete. If you can translate the remaining parts, we will add it to the next version: https://www.transifex.com/aimeos/aimeos-core/

**Comment by vmans** [comment]
I have not seen that "&cHash empty" problem yet. It gives a "page not found"? Is that on links in the product text, or in the process?

**Comment by vmans** [comment]
I translated remaining country names to dutch. I hope they are fine. But all country name translations should be reviewed anyway. I try to find time for that, soon. And also for remaining untranslated/unreviewd phrases.

**Comment by aimeos** [comment]
The cHash problem occurs only in the 16.10.3 version. The 17.2.1 works as expected.

Thanks for your translations. We will update them before releasing the next version.
