### ISSUE TITLE
Versioning of the extension is wrong

### ISSUE THREAD

**Issue by vmans** [aimeos/aimeos-typo3#45]
In the latest emconf.php (https://github.com/aimeos/aimeos-typo3/commit/e381b5fa0f0be009c3a6b8c8ca7ae13a45ca56c7) I find this:
line 15: 
`'version' => '17.1.0',`

The TER in TYPO3 calls it:
`Version	16.10.4 Stable`

And the last one I've installed from TYPO3 TER is... `17.2.1`

We're talking about the same version, I believe. I had issues before with versions, last week as you might recall. Perhaps it's connected.

If I see it correctly, then please update and maintain proper versioning. Thanks!

**Comment by gilbertsoft** [comment]
Have a look at the branch for the 17.x version at https://github.com/aimeos/aimeos-typo3/tree/2017.02, there you find the version you have installed with the extension manager. Changes at the master branch are not fully tested yet and will be merged back to the 2017.02 branch in upcomming releases normally.

**Comment by vmans** [comment]
Thanks. But still...

- In the TYPO3 TER on the typo3.org website, I see clearly "16.10.4" on the webpage and in the emconf.php *.
- My version installed from TER in TYPO3 backend EM is "17.2.1".

It's both "aimeos". Are there 2 branches in TER with the same key? What am I missing here?

* https://typo3.org/extensions/repository/?id=23&L=0&q=aimeos&tx_solr%5Bfilter%5D%5BextensionMinTYPO3Version%5D=&tx_solr%5Bfilter%5D%5BextensionMaxTYPO3Version%5D=

**Comment by gilbertsoft** [comment]
No, 17.x are beta releases yet, you can see the full history of available releases if you click to the download tab at the extension repositry.

If you like to change the installed version go to the extension manager, switch to "Get extensions" and search for "aimeos". Click to the extension title to see the list of the available versions to install.

**Comment by vmans** [comment]
Thanks for your explanation. This is familiar to me.

But when I add translation strings like I did in www.transifex.com/aimeos/, in this case country names, for the Dutch (nl) language and I use version 17.2.1 - which I somehow obtained, I don't know how - how do I get these into my installed system? I can't go back to branch 16.

And also the other important and interesting changes in 16.10.4, I like them too. But not in 17.2.1?

**Comment by aimeos** [comment]
There's no official 17.x version released that contains the changes but you can always check out the dev-master branch yourself and run `composer update`.

**Comment by gilbertsoft** [comment]
The country name po files are located at typo3conf/ext/aimeos/Resources/Private/Extensions/ai-client-html/client/i18n/country, so you only have to put your changed files to this folder or do a checkout as @aimeos wrote.

**Comment by aimeos** [comment]
We strongly suggest to NOT overwrite anything from the core because this will be gone when installing a new version. ALWAYS create your own project-specifc extension and add your changes there.

In case of .po files, you also have to create the associated binary file with `msgfmt`

**Comment by vmans** [comment]
Thanks, and no worries, I have my own extension.
I forgot the nl (the extensionless file). How can I render my own nl file from nl.po? (I'm not a programmer)

**Comment by aimeos** [comment]
Use this Unix command from Gettext:
`msgfmt --statistics -c -o nl nl.po`
