### ISSUE TITLE
Remove required config.baseUrl setting

### ISSUE THREAD

**Issue by vmans** [aimeos/aimeos-typo3#46]
Remove required config.baseUrl setting.
TYPO3 installations do not need the config.baseUrl anymore. Which is very good.

**Comment by aimeos** [comment]
Where did you find the config.baseUrl setting?

**Comment by vmans** [comment]
In the documentation:

https://aimeos.org/docs/TYPO3/Install_Aimeos/Configure_TYPO3

**Comment by aimeos** [comment]
OK, we've added a hint that it's only required for TYPO3 6.2
