### ISSUE TITLE
Salutation not saved when company

### ISSUE THREAD

**Issue by butu** [aimeos/aimeos-typo3#47]
If I newly create a user during checkout, with the salutation company, then the salutation is not saved. I thought maybe i missconfigured something, but I can recreate this behaviour with the aimeos_dist out of the box.

Aimeos 16.10.1
TYPO3 7.6.14

**Comment by aimeos** [comment]
You are right because "officially" the `gender` column (tinyint) in `fe_users` is only defined for "Mr" (0), "Mrs" (1) and "unknown" (99). We've added a custom value for company now (10): ffc53bd

The change will be in the next releases (16.10.5 and 17.4.0)

**Comment by butu** [comment]
Great, thank you! :)
