### ISSUE TITLE
Feature: pick-up locations

### ISSUE THREAD

**Issue by vmans** [aimeos/aimeos-typo3#49]
Quoting page https://aimeos.org/docs/User_Manual/Administration_Interface/Service_details:

"The service attribute panel is available for future uses but we found no case where we need it yet :-)"

Can pick-up locations for the delivery service be a case?

And it would be great if it syncs with fe_user records. Because resellers can be fe_users in TYPO3.

**Comment by aimeos** [comment]
If the pick-up location is where the products are stored in your case, using different stock types (formerly warehouses) would be more suitable. The customers can then select at the product detail page (or before) where they want to pick up the products and you know how many products are available at each location.

Resellers can be added as suppliers but they use their own tables (mshop_supplier*). The supplier list table could be used to associate the stock types (warehouses) to the suppliers/resellers that belong together.

**Comment by vmans** [comment]
Thanks. That makes sense! But also in this case?

- Stock detail must be hidden from customers' sight.
- There is one central website with one central webshop.
- Customers can chose between shipping to their address from central store, or pick-up (no shipping fee) at  a resellers location. If a customer choses pick-up, the order is shipped from central store to pick-up location. Otherwise it's shipped to the customer's address. There is no stock at the pick-up location.

**Comment by aimeos** [comment]
In this case, adding the pick-up stores to the list of delivery addresses in the checkout address page would be more appropriate. They can be retrieved from the fe_users or fe_users_address tables depending on how you want to store and flag them as resellers.
