### ISSUE TITLE
Problems with aimeos email task

### ISSUE THREAD

**Issue by alexingo** [aimeos/aimeos-typo3#5]
Hi, I've installed typo3 7.0.2, aimeos 2.3.1, scheduler and static_info_tables. The scheduler test task and aimeos:jobs:run works. But I've got problems with aimeos:jobs:email:
PHP Catchable fatal error:  Argument 1 passed to Aimeos\Aimeos\Scheduler\Base::execute() must be of the type array, object given, called in /www/htdocs/.../typo3conf/ext/aimeos/Classes/Command/JobsCommandController.php on line 93 and defined in /www/htdocs/.../typo3conf/ext/aimeos/Classes/Scheduler/Base.php on line 30
Best regards!

**Comment by aimeos** [comment]
Thanks for the hint!
This is fixed now with the latest commit and will be part of the next release in 2-3 weeks.
You can use the Aimeos e-mail scheduler instead which fully works in 7.x

**Comment by alexingo** [comment]
Thanks for your reply. Unfortunately I can't create a scheduled task of the type "Aimeos Shop e-mail scheduler". I can't save this form and there are no options for email....
I will wait for the new release! Thank you anyway for this great extension!
![aimeos-task-error2](https://cloud.githubusercontent.com/assets/7010387/10041148/4fda94de-61e2-11e5-935e-306df2b790d3.JPG)

**Comment by aimeos** [comment]
That's strange. Normally, there should be additional options displayed as soon as you select the "Aimeos Shop e-mail scheduler". I've tested with 7.0.2 too and it worked in my installation. Can you find out why this happens in yours?

**Comment by alexingo** [comment]
Because of the error "Internationalization object not available for "en"", I've changed the user settings to German. Now I can see the additional fields to enter email address and so on. But I can't save the task!? The red error block appears like above but without a message!?

**Comment by aimeos** [comment]
Did you deactivate the languages in the admin interface (locale tab -> languages)? That's the only way how I get the same error message like you. Please have a look if "English" and "German" are activated.

**Comment by alexingo** [comment]
It's strange. Englich isn't in my list!?
![language](https://cloud.githubusercontent.com/assets/7010387/10093928/a89e9480-6359-11e5-9464-baff7eb4404e.JPG)

**Comment by aimeos** [comment]
The TYPO3 languages are not relevant. Please have a look into the Aimeos shop admin interface (left navigation menu -> Page -> Aimeos Shop), click on the Locale (Gebietsschema) tab and then on the Languages (Sprachen) tab. German and English should be activated there.

**Comment by alexingo** [comment]
English was deactivated! Thank you very much - Now it  works!
