### ISSUE TITLE
[FEATURE] Use of "Simulate time"

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/aimeos-typo3#50]
The setting "Simulate time" on the FE admin panel is ignored by Aimeos. This is a cool feature of TYPO3 to be able to test things before they are shown to the customers.

E. g. I have a messagebox promoting a discount code which only is shown in specified date range, the coupon has the same validity range. But because Aimeos is ignoring "simulate time" the error message 'Coupon code "ostern2017" is invalid or not available any more' is shown.

For the realisation we need a new interface in ai-typo3 to provide this setting to the core, perhaps https://github.com/aimeos/ai-typo3/blob/master/lib/custom/src/MW/Session/Typo3.php could be the right place. But I never used this as programmer and I don't know how and where this is handled by the CMS. I will provide some more information in short...

**Comment by gilbertsoft** [comment]
I had a quick look at the TYPO3 sources and found the implementation for this feature in https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#L1222

Here the code:

$backendUser = $GLOBALS['BE_USER'];
// Simulate date
$simTime = $backendUser->adminPanel->extGetFeAdminValue('preview', 'simulateDate');
if ($simTime) {
    $GLOBALS['SIM_EXEC_TIME'] = $simTime;
    $GLOBALS['SIM_ACCESS_TIME'] = $simTime - $simTime % 60;
}

More settings can be found in https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/View/AdminPanelView.php#L76

**Comment by gilbertsoft** [comment]
On the Aimeos side I would suggest to define a new function e. g. getTime() for \Aimeos\Client\Html\Common\Client\Factory\Base (if this feature should be used in Aimeos\Client\Html\Account\Watch\Standard too) and \Aimeos\MShop\Common\Manager\Base for all objects.

The interface to the distros could be implemented in \Aimeos\MShop\Context\Item\Standard with a default call to PHP's time() and an override for TYPO3.

Any suggestions?

**Comment by aimeos** [comment]
The context item would need the `getTime()` method which should execute an anonymous function to be flexible. Then, it can be used in the `createSearch()` methods of the managers whose tables have a `startdate` and `enddate` column.

**Comment by gilbertsoft** [comment]
Yes, was my second thought too because every object uses the context. Will make a PR on this next month...

**Comment by aimeos** [comment]
Implemented
