### ISSUE TITLE
Update script produces error while creating foreign key

### ISSUE THREAD

**Issue by jonaseberledmind** [aimeos/aimeos-typo3#54]
On current master:

From the update script called from the Typo3 Extension Manager:
<pre>
  Using schema from customer.php                                      
    Checking table "mshop_customer":                                  done
    Checking table "mshop_customer_address":                          done
    Checking table "mshop_customer_list_type":                        done
    Checking table "mshop_customer_list":                             
An exception occurred while executing 'ALTER TABLE mshop_customer_list ADD CONSTRAINT fk_mscusli_pid FOREIGN KEY (parentid) REFERENCES mshop_customer (id) ON UPDATE CASCADE ON DELETE CASCADE':

SQLSTATE[HY000]: General error: 1005 Can't create table 'playground.#sql-7d5_22f8' (errno: 121)
#0 /var/www/playground.schempp-hirth.com/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Task/Base.php(141): Aimeos\MW\DB\Statement\DBAL\Simple->execute()
</pre>

The funny thing here is the table name. I don't know much about Doctrine but this doesn't look right.

A workaround to get the rest of the column updates currently is to comment out the ->addForeignKeyConstraint() calls in <code>./vendor/aimeos/aimeos-core/lib/mshoplib/setup/default/schema/customer.php</code> temporarily.

**Comment by aimeos** [comment]
Does it work if you comment out creating the index before:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/setup/default/schema/customer.php#L156

You have to remove that index via phpMyAdmin before running the update script again.

**Comment by jonaseberledmind** [comment]
Yep, but then I get 
<pre>
  Using schema from customer.php                                      
    Checking table "mshop_customer":                                  done
    Checking table "mshop_customer_address":                          
An exception occurred while executing 'ALTER TABLE mshop_customer_address ADD CONSTRAINT fk_mscusad_parentid FOREIGN KEY (parentid) REFERENCES mshop_customer (id) ON UPDATE CASCADE ON DELETE CASCADE':

SQLSTATE[HY000]: General error: 1005 Can't create table 'playground.#sql-7d5_2379' (errno: 121)
#0 /var/www/playground.schempp-hirth.com/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Task/Base.php(141): Aimeos\MW\DB\Statement\DBAL\Simple->execute()
</pre>

I tried deleting the tables, then commenting out all "parentid" indices - but no luck.

**Comment by aimeos** [comment]
Can you remove the line creating the index `fk_mscusad_parentid` as well and start over again? There are maybe other index in the customer domain that needs the same treatment.

**Comment by jonaseberledmind** [comment]
I tried commenting out that and went from there from error to error, always commenting out the offending indices or foreign key constraints.

This version runs: https://gist.github.com/anonymous/b87eff3a4798dbb8a794116b9857ef7e
Enabling the indices works as well - it does not seem to make any change to the errors on creating the foreign keys.

**Comment by aimeos** [comment]
Does this version also work if you re-enable the foreign keys?
Which database and version are you using? What's the doctrine DBAL version?

**Comment by jonaseberledmind** [comment]
> Does this version also work if you re-enable the foreign keys?
no, the indices work but the foreign keys can't be created
> Which database and version are you using? 
MySQL 5.5.57-0+deb8u1
> What's the doctrine DBAL version?
doctrine/dbal v2.5.13 (via composer; aimeos/typo3 dev-master requires ~2.4, aimeos/aimeos-core dev-master ~2.0)

**Comment by aimeos** [comment]
Can you post the output of `SHOW CREATE TABLE mshop_customer`?

**Comment by jonaseberledmind** [comment]
<pre>

| Table          | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| mshop_customer | CREATE TABLE `mshop_customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `siteid` int(11) DEFAULT NULL,
  `code` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `label` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `salutation` varchar(8) COLLATE utf8_unicode_ci NOT NULL,
  `company` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `vatid` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `title` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `firstname` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `lastname` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `address1` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `address2` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `address3` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `postal` varchar(16) COLLATE utf8_unicode_ci NOT NULL,
  `city` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `state` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `langid` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `countryid` char(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `telephone` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `telefax` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `website` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `longitude` decimal(8,6) DEFAULT NULL,
  `latitude` decimal(8,6) DEFAULT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `birthday` date DEFAULT NULL,
  `vdate` date DEFAULT NULL,
  `status` smallint(6) NOT NULL,
  `mtime` datetime NOT NULL,
  `ctime` datetime NOT NULL,
  `editor` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unq_mscus_sid_code` (`siteid`,`code`),
  KEY `idx_mscus_sid_langid` (`siteid`,`langid`),
  KEY `idx_mscus_sid_last_first` (`siteid`,`lastname`,`firstname`),
  KEY `idx_mscus_sid_post_addr1` (`siteid`,`postal`,`address1`),
  KEY `idx_mscus_sid_post_city` (`siteid`,`postal`,`city`),
  KEY `idx_mscus_sid_city` (`siteid`,`city`),
  KEY `idx_mscus_sid_email` (`siteid`,`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
+----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

</pre>

**Comment by aimeos** [comment]
OK, no foreign key was created at all. Can you please run this command and post the output:
```
SELECT
  constraint_name,
  table_name
FROM
  information_schema.table_constraints
WHERE
  constraint_type = 'FOREIGN KEY'
  AND table_schema = DATABASE()
ORDER BY
  constraint_name;
```

**Comment by jonaseberledmind** [comment]
No problem

<pre>
+---------------------+------------------------------------+
| constraint_name     | table_name                         |
+---------------------+------------------------------------+
| fk_mscusad_parentid | zzz_deleted_mshop_customer_address |
| fk_mscusli_pid      | zzz_deleted_mshop_customer_list    |
| fk_mscusli_typeid   | zzz_deleted_mshop_customer_list    |
| fk_t3feuli_typeid   | fe_users_list                      |
+---------------------+------------------------------------+
</pre>

**Comment by aimeos** [comment]
OK, that's your problem why the foreign key constraints can't be created:
The tables have been created in the past and you renamed them afterwards. The names of the foreign key constraints stay the same when you rename a table and they share a global database namespace. If you delete those "zzz_deleted_*" tables, than the update script will run without errors.

**Comment by jonaseberledmind** [comment]
Yep, runs without errors. Typo3 is a bitch. Thanks for the help!
