### ISSUE TITLE
Installation creates absolute symlink

### ISSUE THREAD

**Issue by adimit** [aimeos/aimeos-typo3#55]
When using the `composer.json` exactly as indicated in the Readme, the resulting installation correctly puts typo3 in the `htdocs` subfolder *under* the `composer.json`. However, the `ext` folder is linked to by the **absolute** symbolic link `htdocs/typo3conf/ext/aimeos/Resources/Private/Extensions` (e.g. `/home/myuser/myproject/ext`)

Since the symbolic link is absolute, and relative to the developer's machine, a virtual environment, such as a docker container or vagrant machine attempting to run aimeos will fail with cryptic error messages such as `Cannot find /var/www/html/typo3conf/ext/aimeos/Resources/Private/Extensions` — that file *does* exist, but it's a symlink pointing to `/home/myuser/myproject/ext`, which does not exist in the virtualised container.

Unfortunately, `Aimeos\Aimeos\Custom\Composer::install` which is executed in `composer.json:scripts/post-update-cmd` expects said file to be a symlink. Merely moving `ext` to `htdocs/typo3conf/ext/aimeos/Resources/Private/Extensions` will cause that script to fail:

```
Script Aimeos\Aimeos\Custom\Composer::install handling the post-update-cmd event terminated with an exception

                                                                                                          
  [ErrorException]                                                                                        
  unlink(/home/aleks/src/designkatalog/data/typo4/html/typo3conf/ext/aimeos/Resources/Private/Extensions  
  ): Is a directory 
```

I suggest making the symlink relative.

Note that the symlinks `index.php` and `typo3` created by composer are, in fact, relative (probably for the same reason.)

**Comment by aimeos** [comment]
Thank you for reporting this issue!
The current dev-master branch creates relativ symlinks now: a21cd709799b09a9d278a50d7620de96679f78c6
Can you please check if this works for you?

**Comment by adimit** [comment]
Works well, thanks a lot for the fast response.
