### ISSUE TITLE
[BUG] Issues by installing the aimeos under TYPO3 8.7.7 with composer

### ISSUE THREAD

**Issue by dhuf** [aimeos/aimeos-typo3#56]
Same issue with `latest version` and `dev-master`

* The "ext" folder gets created in the root probably linked to the dependency with `composer/installers`, seems that only `typo3/cms-composer-installers` should be used.

**Comment by dhuf** [comment]
Ok, seems that reading this doc helps a bit https://github.com/aimeos/aimeos-typo3#composer but didn't see it here https://aimeos.org/docs/TYPO3/Install_Aimeos/Install_and_configure

**Comment by aimeos** [comment]
Thanks for the hint! We've added the composer section now also to the Wiki:
https://aimeos.org/docs/TYPO3/Install_Aimeos/Composer
