### ISSUE TITLE
Image changer in detail view faults in TYPO3

### ISSUE THREAD

**Issue by AlbiWe** [aimeos/aimeos-typo3#58]
The script doesn´t works as expected, also in the demo shop (http://typo3.demo.aimeos.org/), but
works in Laravel, Symfony.

**Comment by aimeos** [comment]
The problem is the smootscroll code of the bootstrap_package. It prevents setting the hash for the image e.g. "image-1" so the image with that anchor is shown. The only way to get around this was to add this line to the TypoScript setup section:
```
page.includeJSFooterlibs.bootstrap_smoothscroll >
```

**Comment by AlbiWe** [comment]
Ok, I see - works so far. Thx.
Maybe I´ll modify that later.
