### ISSUE TITLE
Question: Add "Save & Close" and "Add" options?

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3#59]
In some sections like the catalog area it is not possible to select a "save & close" option. I don't know, if there is a specific reason for that; if not, is there any chance to add this option?

Also, if I would like to add a subcategory to a selected category, there is no "add" option anywhere. Currently it is required to select "Save & new", which is ... strange... The enclosed image shows that the category "Locations" is selected, but I have no "regular" possibility to add a subcategory.

![screen shot 2018-01-29 at 13 49 57](https://user-images.githubusercontent.com/213803/35511254-77d6a630-04fb-11e8-8925-ed86d0d16702.png)

**Comment by aimeos** [comment]
"Save & close" makes no sense because there's no list view. The tree is always visible on the left.
The "add" button is the blue "+" above the tree view.

**Comment by rowild** [comment]
Well... I dare to disagree. All those operations should be in one spot only. IMHO there is no need for those +/- buttons being in a separate place; they should be where the Cancel/Save buttons are...
And if there is no category selected, a simple text like "Please select a category" should show up... Alway having the edit interface open is kind of weird for an editor... feels like the work is not saved, not finished... and the chance to make an error (like editing the wrong category) is actually quite high.

**Comment by aimeos** [comment]
Hm, the category tab is similar to the TYPO3 page tree / content frame and also the buttons (at least for adding a new category) are similar to the TYPO3 page tree buttons ...

**Comment by rowild** [comment]
Well...the page tree offers an overview of the content element and various buttons (like "view", "edit", "search" and some more on the top right side). It does NOT immediately change into "page edit" state, which is the case in the category tree, where you immediately switch to "edit" mode of the root category, if the section is called for the first time and therefore no other category is/can be selected.

Also, "Save & New" as well as the "+" (for adding a new category) somehow duplicate functionality...

I could imagine something like the enclosed sketch... (just a quick draw)...

![categories-layout](https://user-images.githubusercontent.com/213803/35597238-c85d9d7a-061d-11e8-98d8-fe67763eecab.jpg)
