### ISSUE TITLE
Root catalog deleted, then no catalog creation possible

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3#60]
The catalog tree system seems to be quite buggy. My structure was:
- Root
--- Catalog 1
------ Sub Category
------ Sub Category
------ Sub Category
--- Catalog 2

I moved all Subcategories to Root, Catalog 1 remained as the selected category. Since I wanted to delete this category, I chose the minus button next to the "Find category" search box - and ALL CATEGORIES where gone!!! 

After that, i tried to create a new root category again, but got this error:
No node with ID "0" found, /Volumes/_II_/_SITES/typo3-8.7/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/Tree/Manager/DBNestedSet.php:782

This is happening while playing around with a clean standard installation of the aimeos_dist 17.10 on TYPO3 8.7

**Comment by rowild** [comment]
It seems this happens, when the root category is deleted. Only way is to create it in the DB directly. In my opinion, there should be a safety check on whether the root or any other category is deleted. Also, they should be flagged "deleted" in the DB and not deleted directly. The way it is seems to be very dangerous!

**Comment by rowild** [comment]
And furthermore it is possible to create a "id=0" category in expert mode, but not via the new backend.

**Comment by aimeos** [comment]
OK, the root category shouldn't be removed at the moment. Either we should prevent this or make it possible to add a new root node again.

Deleted is deleted! If you want to disable categories, you should set the status to "Deactivated".

The expert mode is removed in the current 2018.01 version and it isn't a good thing to create a category with ID 0, so it's nothing to cry about ...

**Comment by rowild** [comment]
Fine, deleted = deleted. But you know that this is against the well-known TYPO3 behaviour... Needs two levels of awareness within one system... not user friendly in my opinion, and the chance to accidentally delete something is too high... Is there no chance to implement a "fool-proofer" way?

**Comment by aimeos** [comment]
The root category can be removed and created again. But there was a small JS problem that led to the error message you've got if you delete the root category and immediately recreate it again. This is fixed in dev-master and will be part of the next 2017.10 and 2018.x releases. Thank you for that hint!

**Comment by aimeos** [comment]
Regarding safety checks, there's a message box with a big red button that you are going to delete something and if you really want to do that. Did you see it?

**Comment by rowild** [comment]
Yes, I did. My point is that TYPO3 works differently, as mentioned above. A "deleted" flag is just safer... and one of the really good TYPO3-things. Why not use it? Why two different behaviours? 

Well, I know, why: because aimeos is independent software and has its own rules. 

It is not my goal to make an elephant out of this mosquito. Nevertheless I'd like to bring it to your attention, because I am pretty sure that there will be editors, who will be confused, too. I already see myself in the situation, where I explain to my customer: "In TYPO3 you can't really delete content or pages... unless you are within aimeos, then please be extra careful..." 

I stick to my point: it is just not good from user perspective!

**Comment by aimeos** [comment]
Well, all other frameworks/applications work differently and don't use a "soft delete" so we won't implement it that way. There are discussions about some kind of transaction history where you can undo changes. But that's something for the future.

As the original problem is solved, I will close the issue for now.
