### ISSUE TITLE
Export text categories in expert mode does not work in Chrome

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3#61]
The manual recommends to export and import text for category texts. Found here:
https://aimeos.org/docs/User_Manual/Administration_Interface/Catalog_tree#Export.2FImport_category_texts

Doing so causes the error shown in the screenshot (no export at all).

![screen shot 2018-01-29 at 15 06 24](https://user-images.githubusercontent.com/213803/35514367-412c0b24-0506-11e8-9640-8d7b14fe391f.png)

aimeos_dist 17.10, TYPO3 8.7, Chrome 63 (all extensions disabled)

**Comment by aimeos** [comment]
The ExtJS administation is deprecated in 2017.x and already removed in 2018.x
The text import feature was always problematic - simply don't use it!

The docs are currently reworked to reference the new JQAdm interface only.

**Comment by rowild** [comment]
In that case, please make sure that a id=0 category can be created, when there is none existing. In v2017 this is only possible in expert mode.

**Comment by aimeos** [comment]
We won't touch the ExtJS expert mode any more and concentrate on the new JQAdm interface only

**Comment by rowild** [comment]
Yes, I understood that. And maybe the creation of a new category is possible in v2018, but in 2017 it is not (in "empty" mode)... just in case that is a bug...
