### ISSUE TITLE
[Documentation] mySQL optimization

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3#62]
Following along and testing:
I follow and test these instructions here:
https://aimeos.org/docs/Administrators/Optimize_performance/MySQL#Analyze_and_optimize_cache_tables_regularly

This is, what happens:
- The given tables examples are wrong (change "mshop_catakog_*" to "mshop_*"
- The given DBs do not support OPTIMIZE!!!

**Comment by aimeos** [comment]
Thanks for the hint! We've fixed the table names in the documentation. MySQL (this is what the page is for) does support the "OPTIMIZE" statement.
