### ISSUE TITLE
[Bug] Extension creator 

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3#63]
When creating a 2018 extension with the offered extension creator here:
https://aimeos.org/developer/extensions/

the dependency to aimeos is still [...]-17.99.
It assume it should be 18...  ?
(And the TYPO3 dependency should probably be raised to min 7.6, too?)

**Comment by rowild** [comment]
As can be read here, the version dependency has to be adjusted manually:
https://aimeos.org/docs/TYPO3/Extend_Aimeos

So sorry for the post. I will close this issue again.

**Comment by aimeos** [comment]
Good point nevertheless! We've updated the template extension to set the correct dependency for 18.x versions
