### ISSUE TITLE
Wrong help text with language label

### ISSUE THREAD

**Issue by rowild** [aimeos/aimeos-typo3#64]
In this folder:
Resources/Private/Extensions/ai-admin-jqadm/admin/jqadm/templates/
these files have wrong help texts assigned to the language selection:
attribute/item-image-standard.php
attribute/item-text-standard.php
catalog/item-image-standard.php
catalog/item-text-standard.php
product/item-text-standard.php

(There might be more files; I'll update as I find them.)

Currently it read:
```
<?= $enc->html( $this->translate( 'admin', 'Images will only be shown for that language, useful if the image contains text or is language sepecific' ) ); ?>
```

It probably should be:
"Language (required)"?

If you could confirm that, I could prepare a PR, if that is all right with you - just let me know! Thanks!

**Comment by aimeos** [comment]
You mean that one?
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/templates/product/item-image-standard.php#L161

What's wrong with that text?

**Comment by rowild** [comment]
Actually, the text makes sense in the image templates. But there are text templates (item-text-standard.php), and it seems the help text does not make sense here at the language label:
https://github.com/aimeos/ai-admin-jqadm/blob/f0d00ae4b3b0c47835d6df36c448edb4209de5ea/admin/jqadm/templates/product/item-text-standard.php#L68

It seems that help text was not available in 17.10, but it is in 18.10 ... or am i totally confused now?
Guess I smoked too aimeos today ;-)

**Comment by aimeos** [comment]
I see! Yes, the help text is new in 2018.01 for the language selector in the text sub-panels but wrong as you say. In the image sub-panels it's right. Can you create a PR that changes the help text of the text sub-panels to something like: `Language of the entered texts`?

**Comment by rowild** [comment]
Two questions:
1. This issue should be moved to ai-admin-jqadm. Is that possible (can you do that, because it seems I can't)? Or should I re-open a new issue over there and put a link to it here?
2. I'll prepare the PR with the string you suggest. That string is one that is currently not available in any .po file, right? Not knowing how to handle .po files I'd like to know if there is something else I have to consider, when providing the PR? (I do have an account on transifex, but I do not know how to provide that new string...)
Thanks!

**Comment by rowild** [comment]
Moved to: https://github.com/aimeos/ai-admin-jqadm/issues/24
