### ISSUE TITLE
[BUG] Installation with Composer fails when setting up symlinks

### ISSUE THREAD

**Issue by jfastnacht** [aimeos/aimeos-typo3#65]
When installing Aimeos with Composer under Windows 8, the installation fails with:

```
  [ErrorException]
  symlink(): No such file or directory
```

The problem is the relative path (check http://de2.php.net/manual/en/function.symlink.php#97605) in https://github.com/aimeos/aimeos-typo3/blob/master/Classes/Custom/Composer.php#L51

which can be fixed for example by using an absolute path with `realpath()` and the `__DIR__` magic constant:

```php
symlink( realpath(__DIR__ . '/../../../../../../' . $path), $t3path . '/Resources/Private/Extensions' );
```

**Comment by aimeos** [comment]
We had absolute links before. The main reason why we use relative links is due to installations with staging/live environments that are copied. Is there another way to fix that instead of switching back to absolute paths?

**Comment by AndreasA** [comment]
There are actually mulltiple issues here.

1. The relative path might differ depending on composer.json settings, like web-dir and vendor-dir and therefore could also fail with non Windows OS
1. Not sure why (didn't dig too deep into it) but composer sometimes seems to return relative and sometimes absolute directories, e.g. the package path for typo3-ter/aimeos is absolute but for aimeos/ai-typo3 is relative to current working directory for me.

To fix those issues I would do it like this:
```
<?php

/**
 * @license GPLv3, http://www.gnu.org/copyleft/gpl.html
 * @copyright Aimeos (aimeos.org), 2016
 * @package TYPO3
 */


namespace Aimeos\Aimeos\Custom;


/**
 * Performs setup and installation steps during composer installs
 *
 * @package TYPO3
 */
class Composer
{
    /**
     * Installs the shop files.
     *
     * @param \Composer\Script\Event $event Event instance
     * @throws \RuntimeException If an error occured
     */
    public static function install( \Composer\Script\Event $event )
    {
        $repository = $event->getComposer()->getRepositoryManager();
        $t3package = $repository->findPackage( 'typo3-ter/aimeos', '*' );

        if( $t3package !== null )
        {
            $installer = $event->getComposer()->getInstallationManager();
            $t3path = $installer->getInstallPath( $t3package );
            if (!self::isAbsolutePath($t3path)) {
                $t3path = getcwd() . '/' . $t3path;
            }

            if( ( $package = $repository->findPackage( 'aimeos/ai-client-html', '*' ) ) !== null )
            {
                $event->getIO()->write( 'Installing Aimeos public files from HTML client' );

                $path = $installer->getInstallPath( $package );
                self::copyRecursive( $path . '/client/html/themes', $t3path . '/Resources/Public/Themes' );
            }

            if( ( $package = $repository->findPackage( 'aimeos/ai-typo3', '*' ) ) !== null )
            {
                $event->getIO()->write( 'Creating symlink to Aimeos extension directory' );

                if( file_exists( $t3path . '/Resources/Private/Extensions' ) === false )
                {
                    $path = dirname($installer->getInstallPath( $package ));
                    if (!self::isAbsolutePath($path)) {
                        $path = getcwd() . '/' . $path;
                    }
                    $relativePath = rtrim(self::getRelativePath($t3path . '/Resources/Private/', $path), '/');
                    if (self::isWindows()) {
                        exec('mklink /D ' . escapeshellarg(str_replace('/', '\\', $t3path . '/Resources/Private/Extensions')) . ' ' . escapeshellarg(str_replace('/', '\\', $relativePath)));
                    } else {
                        symlink($relativePath, $t3path . '/Resources/Private/Extensions');
                    }
                }
            }
        }
    }

    protected static function isAbsolutePath($path)
    {
        // On Windows also a path starting with a drive letter is absolute: X:/
        if (static::isWindows() && (substr($path, 1, 2) === ':/' || substr($path, 1, 2) === ':\\')) {
            return true;
        }
        // Path starting with a / is always absolute, on every system
        return $path[0] === '/';
    }

    protected static function isWindows()
    {
        if (!stristr(PHP_OS, 'darwin') && !stristr(PHP_OS, 'cygwin') && stristr(PHP_OS, 'win')) {
            return true;
        }
        return false;
    }

    protected static function getRelativePath($from, $to)
    {
        // some compatibility fixes for Windows paths
        $from = is_dir($from) ? rtrim($from, '\/') . '/' : $from;
        $to   = is_dir($to)   ? rtrim($to, '\/') . '/'   : $to;
        $from = str_replace('\\', '/', $from);
        $to   = str_replace('\\', '/', $to);

        $from     = explode('/', $from);
        $to       = explode('/', $to);
        $relPath  = $to;

        foreach($from as $depth => $dir) {
            // find first non-matching dir
            if($dir === $to[$depth]) {
                // ignore this directory
                array_shift($relPath);
            } else {
                // get number of remaining dirs to $from
                $remaining = count($from) - $depth;
                if($remaining > 1) {
                    // add traversals up to first matching dir
                    $padLength = (count($relPath) + $remaining - 1) * -1;
                    $relPath = array_pad($relPath, $padLength, '..');
                    break;
                } else {
                    $relPath[0] = './' . $relPath[0];
                }
            }
        }
        return implode('/', $relPath);
    }


    /**
     * Copies the source directory recursively to the destination
     *
     * @param string $src Source directory path
     * @param string $dest Target directory path
     * @throws \RuntimeException If an error occured
     */
    protected static function copyRecursive( $src, $dest )
    {
        self::createDirectory( $dest );

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator( $src, \RecursiveDirectoryIterator::SKIP_DOTS ),
            \RecursiveIteratorIterator::SELF_FIRST
        );

        foreach( $iterator as $item )
        {
            $target = $dest . DIRECTORY_SEPARATOR . $iterator->getSubPathName();

            if( $item->isDir() === false )
            {
                if( copy( $item, $target ) === false ) {
                    throw new \RuntimeException( sprintf( 'Unable to copy file "%1$s"', $item ) );
                }
            }
            else
            {
                self::createDirectory( $target );
            }
        }
    }


    /**
     * Creates a new directory if it doesn't exist yet
     *
     * @param string $dir Absolute path of the new directory
     * @throws \RuntimeException If directory couldn't be created
     */
    protected static function createDirectory( $dir )
    {
        $perm = 0755;

        if( is_dir( $dir ) === false && mkdir( $dir, $perm, true ) === false )
        {
            $msg = 'Unable to create directory "%1$s" with permission "%2$s"';
            throw new \RuntimeException( sprintf( $msg, $dir, $perm ) );
        }
    }


    /**
     * Returns the available options defined in the composer file.
     *
     * @param CommandEvent $event Command event object
     * @return array Associative list of option keys and values
     */
    protected static function getOptions( CommandEvent $event )
    {
        return $event->getComposer()->getPackage()->getExtra();
    }
}

```

**Comment by aimeos** [comment]
We need to create a link for the extensions to the ./Resources/Private/Extensions/ folder because the Aimeos TYPO3 extension expects them there but composer stores it relative to the directory where the composer.json is located.

Regarding creating the link, wouldn't it be easier to use something like this?
```php
$extPath = '/../../../../../../' . $path;
$t3extPath = $t3path . '/Resources/Private/Extensions';

if( $extPath, $t3extPath ) === false )
{
    $extPath = realpath(__DIR__ . $extPath);

    if( symlink( $extPath, $t3extPath ) === false ) {
        throw new \RuntimeException( sprintf( 'Failed to create symlink for "%1$s" to "%2$s"', $extPath, $t3extPath ) );
    }
}
```
The composer.json settings for web-dir and vendor-dir doesn't matter. The links are always correct.

Yes, for typo3-ter/aimeos the returned path is absolute but for aimeos/ai-typo3 composer will return a path relative to current working directory. That's an inconsistent behavior of composer (full packages vs. extension packages) but the current code knows that.

**Comment by AndreasA** [comment]
1. You wanted a solution that works with relative paths which the above one does.
As you mentioned copying the whole project folder will fail with absolute links. My solution creates a relative link. But maybe you could use the move simplistic approach and just differentiate between Windows and other OS.

1. However, the proposed $extPath is to simplistic.
For instance, if I set TYPO3 web-path to e.g. to "other-folder/htdocs" it will fails as you need to go back one more folder. If the web-path is "." then you are going back one folder too many. 
Even worse, would be something like "../other-folder/htdocs" as that would even go outside the composer.json path BUT that one is unlikely to happen / be used.
Maybe you could retrieve the TYPO3 web path config to find out how many folders you need to go back instead of the more complex solution.

**Comment by aimeos** [comment]
Windows is used as development environment but rarely for production in our case. Therefore, it's OK if the link is absolute on Windows.

You are right, the solution is simple and won't catch all possibilities but your approach is extremely complex. I haven't found a simple way to match ".", "other-folder/htdocs" and "../other-folder/htdocs" so at the moment we rely on the TYPO3 composer default values.

**Comment by aimeos** [comment]
Proposed fix at the moment: https://github.com/aimeos/aimeos-typo3/commit/93d2122202a33eb53dcf3a2cbfeaee4ae426fc69

**Comment by AndreasA** [comment]
Yes, I agree my solution is quite complex and I would avoid it too if possible :)

Maybe you could retrieve the web-path of the composer.json and count the "amount" of directories to determine the correct backpath? Still not perfect but should be way easier than my proposed solution which probably isn't perfect either :)
Or maybe even easier, provide an option to override the symlink path (relative to EXT root dir)? That way if the default doesn't work they can just override the setting.

**Comment by aimeos** [comment]
Your last suggestion might be a valid option. Can you propose a patch for this?

**Comment by AndreasA** [comment]
I should be able to. But probably not before Thursday or so :)

**Comment by aimeos** [comment]
@jfastnacht Can you please create a pull request with the necessary changes?

**Comment by aimeos** [comment]
Fixed in https://github.com/aimeos/aimeos-typo3/commit/3e740cb65d505b7498b515c0616d8a2cdd84d6dc
