### ISSUE TITLE
Catalog search does not scale correctly on mobile devices on version  18.4.0

### ISSUE THREAD

**Issue by SmallSeedBox** [aimeos/aimeos-typo3#67]
After clean install of version 17.x.x on typo3 version 8.7.x, the catalog search form scales correctly on mobile devices(form, clear button and submit button on the same line). After upgrade to last stable 18.4.0, form is on one line, and clear/submit button under it.

**Comment by aimeos** [comment]
Might be an issue because of changing to Twitter Bootstrap. Do you have a solution for this?

**Comment by SmallSeedBox** [comment]
It seems that changing in html the component class type from "form-group" into "input-group" scales perfectly without any css fidling.
info from here: https://getbootstrap.com/docs/3.3/css/#forms-help-text
 When I have more time I will track the specific code that generates the html if necessary.

**Comment by SmallSeedBox** [comment]
And seems I found the place to modify: 
typo3conf/ext/aimeos/Resources/Private/Extensions/ai-client-html/client/html/templates/catalog/filter/search-body-standard.php

Changing Line 109 : 
<div class="form-inline">
to 
<div class="input-group">
Does the trick.

**Comment by aimeos** [comment]
Thanks a lot! We've also made some other improvements for mobile devices and released a new version of the ai-client-html extension (2018.04.7)
