### ISSUE TITLE
Unable to delete product from Admin product list (Products)

### ISSUE THREAD

**Issue by SmallSeedBox** [aimeos/aimeos-typo3#69]
When trying to delete a product form product list in the administration interface, after the confirmation window and pressing Delete, the application returns the error below and nothing is deleted. 

Error : 
	`Error Unable to call method "getListItems",[...]/typo3conf/ext/aimeos/Resources/Private/Extensions/ai-admin-jqadm/admin/jqadm/src/Admin/JQAdm/Base.php:51 `
  Yet, I am unable to trace the method to understand where the error is sourced. In version 17, there is no such problem.

**Comment by aimeos** [comment]
The problem is already fixed in the composer packages and we will release a new TYPO3 package in TER next week.

**Comment by SmallSeedBox** [comment]
Great. Thanks.
