### ISSUE TITLE
Catalog detail page shows Product item with ID "" not found

### ISSUE THREAD

**Issue by Moongazer** [aimeos/aimeos-typo3#70]
It seem the product ID is not given to the detail page, it always shows 'Product item with ID "" not found'. I've placed the plugin there and made the relations to requiered fields (favorite and watched products), but did not set anything for "Record Storage Page". Hope thats ok because also the product-list view can find all products from the shop without any additional configuration for the storage.

Apache 2.4.23 (Windows)
PHP 7.2.6
TYPO3 8.7.15
Aimeos 18.4.1

**Comment by aimeos** [comment]
You don't need anything in "Records Storage Page". Do you know when the error occurs, e.g. from where the link to the detail page without product ID is coming from?

**Comment by Moongazer** [comment]
It's coming from the "Catalog list" on my entry page, the wired thing is that the URL contains all parameter including the product ID (http://localhost/playground/index.php?id=68&ai%5Bcontroller%5D=Catalog&ai%5Baction%5D=detail&ai%5Bd_name%5D=Demo_article&ai%5Bd_prodid%5D=1&ai%5Bd_pos%5D=0)

My page setup looks like this:
```
- root
  - Aimeos shop (Catalog list)
    - Catalog detail page
    - Favorite products
    - Watched products
```

**Comment by aimeos** [comment]
Thank you for the hint about the root cause of the problem!

Unfortunately, it's not easily possible to check if TS-config is available for all shop pages in the beginning because pages can be moved to another place in the page tree where the relevant TS-config isn't available any more.
