### ISSUE TITLE
reset of UriBuilder and getContext in plugin controller

### ISSUE THREAD

**Issue by s-diez** [aimeos/aimeos-typo3#71]
Setup:
A Aimeos view (\Aimeos\Aimeos\Base\View) is constructed inside the plugin controller (\Aimeos\Aimeos\Controller\AbstractController) through getContext. This sets the prefix "ai" from the given uriBuilder.

Problem:
If the view helper \Aimeos\MW\View\Helper\Url\Typo3 is then used to generate a URL, it resets the UriBuilder completely.
If a new view is constructed afterwards for example through another call of getContext this will again try to set the prefix from the uriBuilder. But the uriBuilder no longer has a prefix as reset was called earlier.

**Comment by aimeos** [comment]
Thank you for your bug report. Would a `clone` for the uriBuilder object help there?
https://github.com/aimeos/ai-typo3/blob/master/lib/custom/src/MW/View/Helper/Url/Typo3.php#L42

**Comment by s-diez** [comment]
Yes seems good to me and solves the issue for me.

**Comment by aimeos** [comment]
Great! Could you create a pull request with the necessary change?

**Comment by s-diez** [comment]
https://github.com/aimeos/ai-typo3/pull/9

**Comment by aimeos** [comment]
Merged
