### ISSUE TITLE
IE 11 and Product -> Variants is not working

### ISSUE THREAD

**Issue by shilgendorff** [aimeos/aimeos-typo3#74]
Hy there

We recognised that the variants function doesn't work at IE 11 (on every system).  

![bildschirmfoto 2018-08-06 um 15 49 43](https://user-images.githubusercontent.com/20240179/43720590-dddaf36c-9990-11e8-8f8e-e093432c2278.png)

Has the support for IE 11 been ended or is there a plan for how long the IE 11 is supported?

Thanks for your Feedback.

**Comment by aimeos** [comment]
That panel uses Vue.JS for rendering the items and the library supports IE9+ IIRC. Is there a JS error message in the browser console?

**Comment by shilgendorff** [comment]
oh this sounds nice. 

no unfortunately there are no messages in the browser console - the browser console is absolutly empty in IE 11.

**Comment by aimeos** [comment]
OK, this makes it difficult to debug ...

**Comment by shilgendorff** [comment]
yes i unterstand this point - for me its absolutly the same problem. 

i just reproduced the problem with the https://app.crossbrowsertesting.com/ tool. 

maybe you will see more it you try it?

**Comment by aimeos** [comment]
IE11 is now used by 1% of all users only so it's not worth optimizing for that browser any more
