### ISSUE TITLE
Possible issue with media attributes.

### ISSUE THREAD

**Issue by SmallSeedBox** [aimeos/aimeos-typo3#76]
Hi, after upgrade from ai 18.4 to 18.7 : 
Php version :  	7.0.32-0ubuntu0.16.04.1
Typo3 version : 8.7.15 
Aimeos version :  	18.7.3 

I seems to find no way to  add records here : `mshop_media_list`, through the admin interface . Before upgrading to 18.7.3, a somewhat managed to add some records here, which are visible as "data-variant-color="10" data-variant-width="11" data-variant-length="12" for each image. If I add an attribute[att_name], type color, with domain 'Media', and after that add it to the products 'Variant attributes', the attribute will change it's domain to 'Product'.  No matter which attribute I add, or change the order (add image after the attribute, or in reverse), the above table is update. If I add records manually in Sql, the image attributes are visible, but does not seem the right way.

Is the automatic domain change by design ? If so, how can the attributes for media be added ? thanks.

**Comment by aimeos** [comment]
Thanks, we will have a look at this and try to reproduce the problem. Please give us a few days as we are currently in the release process for 2018.10

**Comment by aimeos** [comment]
The feature has been accidentially removed in 2018.07 (TYPO3: 18.7.x) but is now back again. It will be in the upcoming 2018.10 LTS release.

**Comment by SmallSeedBox** [comment]
Thanks. After the 2018.10 LTS release, I will test the feature and close the issue if it's solved.

**Comment by SmallSeedBox** [comment]
After a clean upgrade to 2018.10 LTS release, followed by executing the upgrade scripts, when adding an atribute with Domain : Media and Type : Color, I get the following error: 
"No item found for conditions: Array ( [attribute.type.code] => color [attribute.type.domain] => media ) "

**Comment by aimeos** [comment]
For media/color, no attribute type is created by default, only the attribute type for product/color. You have to go to the "Types -> Attributes" panel add it there first.

**Comment by SmallSeedBox** [comment]
Tested & works perfectly. Thank you.
