### ISSUE TITLE
DefaultTableOptions from LocalConfiguration.php

### ISSUE THREAD

**Issue by noll1** [aimeos/aimeos-typo3#79]
In EXT:aimeos/Resources/Private/Config/resource.php you load the charset and collation for tables as follows:
```
'defaultTableOptions' => array(
	'charset' => ( isset( $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['tableoptions']['charset'] ) ? $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['tableoptions']['charset'] : 'utf8mb4' ),
	'collate' => ( isset( $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['tableoptions']['collate'] ) ? $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['tableoptions']['collate'] : 'utf8mb4_bin' ),
),
```
But in a fresh Typo3 v9.5.0 LTS environment the charset and collation config is under ...['Default']['tableoptions']['charset'] & ...['Default']['tableoptions']['collate'].
For example the 'DB' part of LocalConfiguration.php:
```
'DB' => [
    'Connections' => [
        'Default' => [
            'charset' => 'utf8mb4',
            'dbname' => '******',
            'driver' => 'mysqli',
            'host' => '127.0.0.1',
            'password' => '******',
            'port' => 3306,
            'tableoptions' => [
                'charset' => 'utf8mb4',
                'collate' => 'utf8mb4_unicode_ci',
            ],
            'user' => '******',
        ],
    ],
],
```

**Comment by aimeos** [comment]
Yes, that's true. `utf8mb4_bin` is case sensitive and compatible with other DBMS (MySQL is the only one that's using case insensitive collation). The main reason for `utf8mb4_bin` is the support for NoSQL storages in 18.10, which can generate unique IDs that only differ in character case (ElasticSearch for example)

**Comment by noll1** [comment]
Sorry, I've done a misstake in the upper grey box of my first post.
You load the config in the resource.php as follow:
```
'defaultTableOptions' => array(
	'charset' => ( isset( $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['charset'] ) ? $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['charset'] : 'utf8mb4' ),
	'collate' => ( isset( $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['collate'] ) ? $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['collate'] : 'utf8mb4_bin' ),
),
```
It should replace with this:
```
'defaultTableOptions' => array(
	'charset' => ( isset( $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['tableoptions']['charset'] ) ? $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['tableoptions']['charset'] : 'utf8mb4' ),
	'collate' => ( isset( $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['tableoptions']['collate'] ) ? $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default']['tableoptions']['collate'] : 'utf8mb4_bin' ),
),
```
You forgot the level ['tableoptions'].

**Comment by aimeos** [comment]
OK, that's a bug and now fixed in https://github.com/aimeos/aimeos-typo3/commit/289d2399fca53d5d42bbde7dc1f2055beadb4950
We are also using `utf8_bin` now as default value for TYPO3 7/8. Otherwise, people using MySQL 5.5 or 5.6 will see errors.

Thank you for your help :-)
