### ISSUE TITLE
SEO URLs and product sitemap scheduler job

### ISSUE THREAD

**Issue by s-diez** [aimeos/aimeos-typo3#82]
I'm currently trying to generate a sitemap using the "Product site map" job of the "Aimeos Shop scheduler".
Everything seems to work as expected except no SEO URLs are generated through realurl.
After a litte debugging this is not surprising as the task is executed in the backend context without a TypoScriptFrontendController. Am I missing something or does sitemap generation not work with realurl and never has?

I can provide some context to the TypoScriptFrontendController, if necessary and maybe even provide a pull request with a working version.

**Comment by s-diez** [comment]
Nevermind the task Email6 (Aimeos Shop advanced scheduler) does create a TypoScriptFrontendController. Is there documentation for this? As I could not find anything and I wasted quite some time debugging the wrong URLs.

**Comment by aimeos** [comment]
https://aimeos.org/docs/TYPO3/Install_Aimeos/Configure_scheduler_tasks
