### ISSUE TITLE
Plugin for editable list of products

### ISSUE THREAD

**Issue by s-diez** [aimeos/aimeos-typo3#83]
Hi,

I talked with Norbert at the beginning of november and he mentioned, you would be interested in my plugin for an editable list of products. Similar to the regular list plugin, but instead of selecting a category or attribute filters, you can choose directly which products you want to be displayed.

How would you like this feature? Should I create a new extension and send you the GitHub link or would you be interested to integrate this into this extension?

My current implementation of the plugin, consists of the following parts.
- Flexform Helper to get the available products from aimeos and make them selectable in the TYPO3 backend.
- The plugin itself, similar to the regular list plugin. It uses the list client described below and regular list templates. The controller just reads some configuration from flexform settings and sets the corresponding Aimeos config values.
- An extended catalog lists client where `createProductListFilter` reads the configured list of product ids and creates a matching filter condition. If no sorting exists or the sorting is by relevance, it sorts the list in the order of the product ids
- A decorator for the catalog index manager to add the necessary search config to allow sorting a product list by product ids. To use this with PostgreSQL it would probably need adaptation.

**Comment by aimeos** [comment]
Yes, we would be very interested in that feature!
Regarding the last point it would be better to sort the items in the HTML client instead of the pushing this to the database. Because a configured list of product ids isn't that long and there's no reason to let the database to that.

Can you start with a PR for the HTML client so we can integrate the base code first?

**Comment by s-diez** [comment]
> Regarding the last point it would be better to sort the items in the HTML client instead of the pushing this to the database. Because a configured list of product ids isn't that long and there's no reason to let the database to that.

My current version still supports pagination which requires sorting in the database as far as I'm aware. Would you prefer a version which sets the slice/page size  to the number of product ids?

Is there some intended way to sort the list in php or should I just do it in searchProducts after retrieving the list from the controller?

Furthermore my current version still supports filtering the list by attributes or categories as the product id limitation is just added to the default search restrictions created by `Aimeos\Client\Html\Catalog\Base::createProductListFilter` should I remove this part? I'm not quite sure what would be needed to make the count plugin compatible to limit the filters based on the product ids as we do not use it.

**Comment by s-diez** [comment]
I'll start with the pull request maybe some stuff will be easier to explain with a WIP pull request.

**Comment by aimeos** [comment]
PR is open and WIP so I close the issue
