### ISSUE TITLE
Price disappear after "Save & Close"

### ISSUE THREAD

**Issue by noll1** [aimeos/aimeos-typo3#84]
In a fresh Typo3 v9.5.1 environment I've installed Aimeos 18.10.2.
After I've added a price to a product, saved it, opened it again and clicked save & close the price disappear.
Detailed steps to reproduce:
1. Open the "Demo article".
2. Add new price: ![new_price](https://user-images.githubusercontent.com/42864489/49209174-1a915980-f3ba-11e8-99e4-703cbc8704f7.png)
3. Click "Save" and notice that the price is saved.
4. Go back to products with the button on the left tabbar.
5. Open the "Demo article" again.
6. Switch to prices (new price is still there) and click "Save & Close".
7. Open the "Demo article" and see on prices tab that the new price is missing.

**Comment by aimeos** [comment]
We are unable to reproduce that behavior with dev-master and the latest stable composer packages.
Are you using the package from TER?

**Comment by noll1** [comment]
Try it again with a start date in the future (e.g. 2019-01-01T00:00:00).

**Comment by aimeos** [comment]
OK, using a start date in the future reveals the behavior you've described. We will see where the problem is and come back with a solution

**Comment by aimeos** [comment]
The problem has been fixed in the 2018.10 branch. If you use composer, you can add this to the `require` section of your `composer.json`:
```
"aimeos/ai-admin-jqadm": "2018.10.x-dev"
```
After executing `composer update`, the new package is available and you can test it yourself. We will tag a new version soon.

**Comment by noll1** [comment]
Thank you for fast resolving the bug!
