### ISSUE TITLE
Missing directory on composer install

### ISSUE THREAD

**Issue by ghost** [aimeos/aimeos-typo3#86]
Currently testing in TYPO3 v9, after a `composer req "aimeos/aimeos-typo3:@dev"` when trying to enable aimeos in the extension manager the directory `typo3conf/ext/aimeos/Resources/Private/Extensions/` is expected to be existent:

<pre>
UnexpectedValueException

DirectoryIterator::__construct(/var/www/html/typo3conf/ext/aimeos/Resources/Private/Extensions/): failed to open dir: No such file or directory
in /var/www/html/vendor/aimeos/aimeos-core/Bootstrap.php line 287
</pre>

**Comment by aimeos** [comment]
You forgot to add the post install scripts to your composer.json:
https://github.com/aimeos/aimeos-typo3#composer

```
    "scripts": {
        "post-install-cmd": [
            "Aimeos\\Aimeos\\Custom\\Composer::install"
        ],
        "post-update-cmd": [
            "Aimeos\\Aimeos\\Custom\\Composer::install"
        ]
    }
```

**Comment by aimeos** [comment]
Can you have a look why it's not created in your environment? Your composer output says it was done:
`Creating symlink to Aimeos extension directory`

You can find the link creating code there:
https://github.com/aimeos/aimeos-typo3/blob/master/Classes/Custom/Composer.php

**Comment by jonaseberledmind** [comment]
I got it. It creates a symlink Extensions -> ../../../../../../ext
which might be correct for a pure TYPO3 composer install but I am working on TYPO3 master.
There the symlink should be ../../../../../ext - that is where the composer install put the aimeos extensions.

**Comment by aimeos** [comment]
That's hard do distinguish and for all "standard" TYPO3 versions (non-dev) this works correctly.
Or will this be a problem in TYPO3 v10?

**Comment by jonaseberledmind** [comment]
AFAIK there will be no changes to the composer structure in v10.
It would be desirable to be able to work with TYPO3 from sources (e.g. to try compatibility with a patch from https://review.typo3.org, test against newest master, ...).

`$event->getComposer()->getPackage()->getExtra()['typo3/cms']['web-dir'] ?? ''` would be empty in a TYPO3 from sources while set to "web"/"htdocs"/"public" (or empty something else) in a TYPO3 composer install.

So to improve on the current state we would need the root-composer.json-path (which my composer-voodoo did not succeed to give me...), append `($event->getComposer()->getPackage()->getExtra()['typo3/cms']['web-dir'] ?? '') . '/typo3conf/ext'`

**Comment by aimeos** [comment]
This could to the job:
`dirname(\Composer\Factory::getComposerFile())`

Can you create a PR with the required changes?

**Comment by meisterkaiser** [comment]
using an absolute path for the symlink using 
`dirname(\Composer\Factory::getComposerFile())`
or similar tricks unfortunately do not work in deployment environments like gitlab ci,
where the symlink is created during build stage and would reflect the absolute path while building the project,
not the path on the machine serving the website.

Need some more testing/improving on a solution to determine the relative path from a given project structure in a reliable way.

**Comment by aimeos** [comment]
This problem is gone since moving extensions to the ./vendor/ folder.
