### ISSUE TITLE
Supported TYPO3 Version does not match API usage

### ISSUE THREAD

**Issue by jonakieling** [aimeos/aimeos-typo3#87]
Hey everyone!

This line linked below is not supported by older TYPO3 Versions since the resetConnections in TYPO3\CMS\Core\Database\ConnectionPool just got introduced in 9.5 last June.

The main issue is, that composer.json and em_conf.php both allow these older TYPO3 versions.

We are using TYPO3 8.7.22 with aimeos/aimeos-typo3 ~18.7

https://github.com/aimeos/aimeos-typo3/blob/dc18fe8b29e66ad6536f82eae2ae051385a361d9/Classes/Scheduler/Base.php#L39

Let me know if I can be of any help!

Best regard
Jonathan

**Comment by aimeos** [comment]
You are right and it's already fixed in 2018.10.x-dev. Will be part of the next release

**Comment by nvindice** [comment]
@aimeos When is this release to be expected? Every scheduler tasks fails atm, which makes my shop unusable...

**Comment by aimeos** [comment]
18.10.3 is still only available via composer, so please use "aimeos/aimeos-typo3": "2018.10.x-dev" at the moment to get the fixed version

We are still having problems uploading new versions to TER and this deferrs any new release ...

**Comment by aimeos** [comment]
Upload to TER works again and new version (18.10.4) is available
