### ISSUE TITLE
[QUESTION] Number format in email - depending on locale?

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#88]
Hi,

I know how to set the number format, depending on the TYPO3 language on a normal page, just part of the normal language setup.
However, how can I make a corresponding distinction for emails which are part of the scheduler tasks?

I would need to set it according to the aimeos locale instead, but not sure how to achieve this in the best way.

**Comment by aimeos** [comment]
The question is smart but there's no good answer yet. The number view helper can't be set up depending on the locale in the scheduler task and the number format can't be changed via translation ...

**Comment by AndreasA** [comment]
OK. So I guess currently the only solution would be to override the adding of the number format helper by setting `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['aimeos']['aimeos_view_number']`
and modifying the configuration options depending on the context locale / languageID?

**Comment by aimeos** [comment]
The next version will use the PHP NumberFormatter class to solve the problem:
http://php.net/manual/en/class.numberformatter.php
