### ISSUE TITLE
Class 'Aimeos\Aimeos\Base' not found

### ISSUE THREAD

**Issue by vmans** [aimeos/aimeos-typo3#90]
Typo3 9.5.4 and Aimeos 18.10.4
The whole TYPO3 installation crashes after install of aimeos.

![image](https://user-images.githubusercontent.com/25581914/51574603-c92fb300-1eae-11e9-9496-9193f660854f.png)

**Comment by vmans** [comment]
Hi, thanks.

After removing typo3temp directory, I got a step further.
But this message came up, when going into the Aimeos module. Not easy to add items this way ;-). I have not made a setup yet (I don't want to use bootstrap_package), but I have run the database update and so on.  I might be missing something, or is it an error?

(1/1) Aimeos\MShop\Exception
No item found for conditions: Array ( [locale.site.code] => default )

in /var/www/clients/client35/web230/web/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php line 478

**Comment by aimeos** [comment]
We had problems with 18.10.4 too, the linked 18.10.5 works for us.

The setup process didn't succeed and the data hasn't been added. If you have already installed the linked 18.10.5 pre-release, please run the update script in the Extension Manager again

**Comment by vmans** [comment]
Hi again, and thanks again,

The update script leaves me with this error (which I thought I had solved with removing typo3temp):

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

More on that from the log:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #42000: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes | Aimeos\MW\DB\Exception thrown in file /var/www/clients/.../.../web/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Statement/DBAL/Simple.php in line 91.

**Comment by aimeos** [comment]
You are using MySQL < 5.7.x which is unable to handle long indexes produced by utf8mb4 charset. You can configure `utf8` instead but you have to remove the tables and run the setup script again. Before, change this in your LocalConfiguration.php file:
```
'DB' => [
    'Connections' => [
        'Default' => [
            'tableoptions' => [
                'charset' => 'utf8',
                'collate' => 'utf8_bin',
            ],
            // ...
        ],
    ],
],
```

**Comment by vmans** [comment]
Okay, thanks! That's wisdom.

I'm in the lucky situation of starting up the whole installation from zero, so I will simply attach a new DB with utf8 in stead of utf8mb4.

**Comment by vmans** [comment]
Hi again. Upgrading then to 19.1.0 brings back the issues, despite the correct settings. And by the way, we use MariaDB and it's hard to tell which exact MySQL version corresponds with that.

![image](https://user-images.githubusercontent.com/25581914/51665439-0fbf0380-1fbc-11e9-985f-fe20a9d099ec.png)

![image](https://user-images.githubusercontent.com/25581914/51665580-62002480-1fbc-11e9-8c61-6d38243a1b75.png)

![image](https://user-images.githubusercontent.com/25581914/51665744-c9b66f80-1fbc-11e9-840a-1fbce406306a.png)

**Comment by aimeos** [comment]
You have a mix of collations (utf8_bin and utf8mb4_bin) in your database according to the output from phpmyadmin. If you drop and recreate all tables, it should work with 19.1.0 too (remember, this version is beta and only for testing).

**Comment by vmans** [comment]
Hi, that's the whole point. I dropped and recreated the tables three times now, and every time these five tables appear as utf8mb4_bin. But only in 19.1.0. If I use 18.10.5 is goes well.

**Comment by vmans** [comment]
I dug deeper into this. But I have limited knowledge, so I can be wrong on this.

As I understand it, to make this 19.1.0 version of Aimeos work, I need a database with utf8mb4 set (which I do default). The same goes for 18.10.5. To make that last one run on my server, I can set it to utf8. And it works! This can not be done for 19.1.0.

But what exactly does Aimeos (Lavarel?) test on, here. It looks like `SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes` is typical for Lavarel. I find similar issues where MySQL5.7.21 is used.

And I use Maria DB 10.1.34. Now, `SHOW CHARACTER SET LIKE 'utf%'` outputs, amongst others, this:

`utf8mb4 | UTF-8 Unicode | utf8mb4_general_ci | 4`

So it seems I meet the requirements to have it working. But is doesn't. I suspect something else is going on. Do you agree?

**Comment by aimeos** [comment]
Laravel was the first framework that used utf8mb4 but TYPO3 v9 does this now too. The problem is that up to 5.7.8 (or something like this) MySQL allows only short indexes but Aimeos has a few indexes that are longer when utf8mb4 is used as charset. For MariaDB it seems to depend on the minor version (10.2 or 10.3).

**Comment by aimeos** [comment]
Compatibility improvements to use Aimeos 19.x with MySQL <5.7 and MariaDB <10.3 are discussed in this issue: https://github.com/aimeos/aimeos-typo3/issues/92

We will need someone that tests on MariaDB later on, maybe you can help?
