### ISSUE TITLE
Error with Database analyzer

### ISSUE THREAD

**Issue by wikafi** [aimeos/aimeos-typo3#91]
Hello, i have an arror with the latest stable version (18.10.4) when I ask to do an analysis of the table after a upgrade

![snip20190123_15](https://user-images.githubusercontent.com/46966266/51613319-80fea800-1f23-11e9-87e5-993192657af8.png)

**Comment by aimeos** [comment]
The error is very strange because it's not related to Aimeos directly but there's a 18.10.5 pre-release that works fine: https://aimeos.org/fileadmin/download/aimeos_18.10.5.zip

Can you give it a try?

**Comment by aimeos** [comment]
Fixed in 18.10.5
