### ISSUE TITLE
[Feature][19.1.0] Compartibility to MySql 5.6

### ISSUE THREAD

**Issue by guelzow** [aimeos/aimeos-typo3#92]
Hi everyone.

I'm not sure, if this is the right place to ask this, so many repos to choose from 😃 

I just tried to install the 19.1.0 on a TYPO3 9.5.4 and get a SQL error during the setup.
Turns out, that the setup tries to create a table where a key is longer than 767 bytes.

```sql
CREATE TABLE mshop_attribute (
    id INT AUTO_INCREMENT NOT NULL,
    siteid INT NOT NULL,
    type VARCHAR(32) NOT NULL,
    domain VARCHAR(32) NOT NULL,
    code VARCHAR(255) NOT NULL,
    `label` VARCHAR(255) NOT NULL,
    pos INT NOT NULL,
    status SMALLINT NOT NULL,
    mtime DATETIME NOT NULL,
    ctime DATETIME NOT NULL,
    editor VARCHAR(255) NOT NULL,
    UNIQUE INDEX unq_msatt_sid_dom_cod_ty (
        siteid,
        domain,
        code,
        type
    ),
    INDEX idx_msatt_sid_dom_label (
        siteid,
        domain,
        `label`
    ),
    INDEX idx_msatt_sid_dom_pos (
        siteid,
        domain,
        pos
    ),
    PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB
```

MySql 5.6 and below exits here with a 

> #1071 - Specified key was too long; max key length is 767 bytes

So:
I would like to request the MySql compartibility to version 5.6 and below.

Tobi

**Comment by aimeos** [comment]
Please read here: https://github.com/aimeos/aimeos-typo3#database-setup

**Comment by guelzow** [comment]
Cool. That worked like a charm.
Can we change the ticket to 'Inform backend user about incompatible db configuration'?

Tobi

**Comment by aimeos** [comment]
How do you want to achieve that? You will only notice if you execute the setup script or command and get an error from the database

**Comment by guelzow** [comment]
You can ask mysql for it's version with 'SELECT version();'

**Comment by aimeos** [comment]
Can you make a PR for that? MariaDB might be affected as well

**Comment by guelzow** [comment]
I have an idea or two, how to tackle this matter. Not sure how it will play out until I've tried.
Current workload is also an issue.

I'll see what I can do.

Tobi

**Comment by aimeos** [comment]
@vmans may help with MariaDB tests

**Comment by aimeos** [comment]
Implemented and merged
