### ISSUE TITLE
Tables having one or more indexes using varchar(255) columns should have ROW_FORMAT=DYNAMIC

### ISSUE THREAD

**Issue by woepwoep** [aimeos/aimeos-typo3#95]
When running the aimeos install script from the extension manager, at some tables the script fails with a message saying the index is too big. this is due to utf8_mb4 usage in combination with varchar(255) fields in a multi-field btree index. Example: mshop_customer indexes (several of them).

Solution is NOT to change to utf8_unicode_ci, because then still some indexes have size > 767

Proposed solution is to have "ROW_FORMAT=DYNAMIC" at the end of table creation;
or have the script run "alter table {here-the-table-name} ROW_FORMAT=DYNAMIC; " before checking the indexes

**Comment by aimeos** [comment]
Unfortunately, it doesn't work as we need to set the new table format to "Barracuda" first (`SET GLOBAL innodb_file_format='Barracuda'`) and this requires SUPER privileges not available in hosting environments:
`Access denied; you need (at least one of) the SUPER privilege(s) for this operation`

Using utf8 instead doesn't create indexes longer than 767 bytes in the Aimeos tables (usually only customer and address tables are affected).

**Comment by woepwoep** [comment]
using utf8 didn't help us today.
varchar(255) as one of the fields, with 3 bytes per character in utf-8, reaches already the limit
(limit: 767; 255*3=765). just one extra field like an INT and the limit is already surpassed.
so the solution proviced - utf8 - is not adequate.
thx Ron

**Comment by aimeos** [comment]
The longest indexes in Aimeos always fit into that limitation if utf8 is used and for MySQL 5.7+ and MariaDB 10.2+, utf8mb4 will be used by default. If you use MySQL 5.5/5.6 or MariaDB < 10.2 and you have the possibility to set `innodb_file_format='Barracuda'`, please do so. In a standard hosting environment it's simply not possible and if we only add `ROW_FORMAT=DYNAMIC` to the `CREATE TABLE` statements, they will fail for MySQL < 5.7.
