### ISSUE TITLE
Typo3 Productimage Filesystem not configured

### ISSUE THREAD

**Issue by loadednet** [aimeos/aimeos-typo3#98]
Using Typo3 8.7.24 and Aimeos 19.1.0:
When adding an image to a product the following error occurs.
 Error File system not configured, ....typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/Filesystem/Factory.php:32

Tested latest 18.x.x verison as well. The error does not occur in the v18!

**Comment by aimeos** [comment]
Do you have a composer based installation?

**Comment by loadednet** [comment]
No. I installed it via TER. Typo3 Installer.

**Comment by aimeos** [comment]
Can you try that package and see if it works?
https://aimeos.org/fileadmin/download/aimeos_19.1.1-pre1.zip

**Comment by loadednet** [comment]
Tested your 19.1.1-pre1. Unfortunately the same error occurs.
Using
Ubuntu v18
Typo3 8.7.24
Aimeos 19.1.1-pre1
Mysql 5.7.25
PHP 7.2.15
Apache 2.4.29
Using symlinks for Typo3 core path (typo3, typo3_src and index.php)

**Comment by aimeos** [comment]
We can reproduce the problem. Aimeos 19.1.0 works with TYPO3 9.5 but throws the error when 8.7 is the host system. We are still investigating why what is the difference between the TYPO3 versions.

**Comment by aimeos** [comment]
Problem found. Can you try this pre-release?
https://aimeos.org/fileadmin/download/aimeos_19.4.0-pre1.zip

**Comment by loadednet** [comment]
Hi,
thank you for you pre package, upload is working. (Error message is gone).
Unfortunately, a different error pops up, that prevents saving the product. After filling in the main credentials and uploading an image, when you click save this error occurs.

Error No item found for conditions: Array ( [attribute.code] => custom [attribute.domain] => product [attribute.type] => price )

I will also try to figure it out. I just wanted to let you know. And thank you for your great support.

**Comment by aimeos** [comment]
The new error is due to the removal of the custom price attribute in the attribute panel you've done. Aimeos needs this to allow custom pricing of products.
