### ISSUE TITLE
Export products xml

### ISSUE THREAD

**Issue by wikafi** [aimeos/aimeos-typo3#99]
Hello,

I configured via Sheduler an export of the product catalog in xml.
The file is created properly but it seems that the contents of the different descriptions are not complete ...

can you help me?

![Snip20190325_1](https://user-images.githubusercontent.com/46966266/54912960-08e83a80-4ef2-11e9-85f5-aa88f10a1880.png)

**Comment by wikafi** [comment]
This is via Typo3 plugin...

**Comment by aimeos** [comment]
Thank you for your bug report. This patch fixes the problem and it will be part of the next release: https://github.com/aimeos/ai-controller-jobs/commit/ad6f7013b904babf3315d3b9dd428257eb9ff21c

**Comment by wikafi** [comment]
Thank you for your answer, but I do not have the file you fill me in my tree ...

![Snip20190325_2](https://user-images.githubusercontent.com/46966266/54927350-4c52a100-4f12-11e9-94e1-2d78c12db598.png)
![Snip20190325_3](https://user-images.githubusercontent.com/46966266/54927352-4ceb3780-4f12-11e9-8a97-20fb39a7bac1.png)

**Comment by wikafi** [comment]
I think the file is rather: items-body-standard.xml ?

Thks

**Comment by aimeos** [comment]
For 2018.10 it's https://github.com/aimeos/ai-controller-jobs/commit/e9d928e757f4fbd6a2dca792f005aa499ded9470
